sleuthkit/autopsy

Core/src/org/sleuthkit/autopsy/modules/photoreccarver/PhotoRecCarverFileIngestModule.java

Note that there are Viking, Autopsy, and Sleuthkit changes to enable successful deletion.

close file handles appropriately

---

Core/src/org/sleuthkit/autopsy/casemodule/OpenFromArguments.java
Core/src/org/sleuthkit/autopsy/corecomponents/Installer.java

Won't do much unless manual association of .aut files to a correct autopsy executable, or the advanced installer correctly associates the right autopsy.exe to open the .aut file

added double clicking to open .aut files

---

Core/src/org/sleuthkit/autopsy/report/Bundle.properties
Core/src/org/sleuthkit/autopsy/report/ReportGenerator.java
test/script/regression.py

Three changes have been made
Diff Util used the HTML report files comparison instead of the chunk comparisons.
ReportGenerator.java is modified to sort the keyword hits and hash set hits so that the report is in the same order each time.
Comments are added in Bundle.properties to notify dependence of regression testing script.

Regression test fix

---

test/script/regression.py

Wrong variable was used. 
Error rectified.

appropriate instance variable used

---

Core/src/org/sleuthkit/autopsy/modules/stix/EvalDomainObj.java
Core/src/org/sleuthkit/autopsy/modules/stix/EvaluatableObject.java
Core/src/org/sleuthkit/autopsy/modules/stix/STIXReportModule.java
docs/doxygen-user/stix.dox

Added Domain Name Object parsing.

---

Core/src/org/sleuthkit/autopsy/report/ReportGenerator.java

SQL query syntax fixed

---

Core/src/org/sleuthkit/autopsy/report/ReportGenerator.java

blackboard_attributes had multiple aliases in he SQL query (att1. att2, att3). Replaced it by single alias- att.

Multiple aliases for blackboard_attributes removed

---

Core/src/org/sleuthkit/autopsy/report/ReportGenerator.java

Reverts sleuthkit/autopsy#1038

Revert "Multiple aliases for blackboard_attributes removed"

---

Core/src/org/sleuthkit/autopsy/report/ReportGenerator.java

1. List of error created.
2. List of error displayed using MessageNotifyUtil in the SwingWorker done()

Error reporting bubble

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/GlobalListsManagementPanel.java

The newly added keywordsList is always appended to the existing list of keywordsLists.
setRowSelectionInterval(int, int) highlights/selects *that* newly added keywords list.

newly added keyword list is selected by default

---

Core/src/org/sleuthkit/autopsy/ingest/IngestManager.java

Add logging of individual job cancellations to IngestManager

---

Core/src/org/sleuthkit/autopsy/core/Installer.java
Core/src/org/sleuthkit/autopsy/coreutils/Logger.java

Logger appropriately logs the method which throws the exception.
Developer log has timestamp resolution in  milliseconds.
The logger handlers are closed before exit.

Logs appropriate method in case of exception. Lck files deleted.

---

Core/src/org/sleuthkit/autopsy/corecomponents/Bundle.properties
Core/src/org/sleuthkit/autopsy/corecomponents/OfflineHelpAction.java
Core/src/org/sleuthkit/autopsy/corecomponents/OnlineHelpAction.java
build.xml

Note that "Package as Zip" and "Build Installer" now require Doxygen to be installed and in your path.

Add offline help files to Help menu

---

Core/src/org/sleuthkit/autopsy/casemodule/StartupWindow.java
Core/src/org/sleuthkit/autopsy/modules/stix/STIXReportModule.java
Core/src/org/sleuthkit/autopsy/report/ReportGenerator.java
Core/src/org/sleuthkit/autopsy/report/ReportKML.java

This reverts commit b1284625d220c203467112afe26441aeba941fdc.

Revert "Revert "used non deprecated complete(ReportStatus)""

---

Core/src/org/sleuthkit/autopsy/modules/stix/EvalDomainObj.java
Core/src/org/sleuthkit/autopsy/modules/stix/EvalFileObj.java
Core/src/org/sleuthkit/autopsy/modules/stix/STIXReportModule.java

Reset ID maps between files.
Allow for multiple hash values in Hash Object.

Bug fixes for STIX module.

---

Testing/test/qa-functional/src/org/sleuthkit/autopsy/testing/RegressionTest.java
test/script/regression.py
test/script/regression_utils.py

Reverts sleuthkit/autopsy#1152

Revert "Add logical files set to regression tests"

---

test/script/regression.py
test/script/tskdbdiff.py

Command and its options have to be passed as separate strings.

cmd and its options tokenized

---

test/script/regression.py
test/script/tskdbdiff.py

Reverts sleuthkit/autopsy#1188

Revert "cmd and its options tokenized"

---

test/script/regression.py
test/script/tskdbdiff.py

Reverts sleuthkit/autopsy#1187

Revert "side by side comparison in diff output"

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableAttribute.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/DrawableTile.java

Added exception handling for an error coming up when Autopsy was closed.

Fixed date format in ImageGallery details pane.

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryModule.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/grouping/GroupManager.java

Fixed bug where removing the final image in a group would leave it in an unanalyzed state.

Added bitmap MIME type to Image Gallery.

---

test/script/regression.py

PyCharm added those indentations. They reappear even after removing them.

additional files with prefixed imagename removed from result folder

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/CategorizeAction.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableDB.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/grouping/DrawableGroup.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/grouping/GroupManager.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/SlideShowView.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/navpanel/NavPanel.java

Changing sort method and ascending/descending now updates the GUI immediately.
Properly decrement uncategorized file count.
Fixed a few case-closing exceptions.

Sorting by file count now works correctly.

---

Core/src/org/sleuthkit/autopsy/directorytree/DirectoryTreeFilterNode.java

1. Run ingest module option is available at image/root virtual directory(logical files set) level only.
2. Open file search by attributes option is available for logical files set as well.

Ingest modules run at ds level

---

Core/src/org/sleuthkit/autopsy/corecomponents/FXVideoPanel.java

Javafx supported extensions revised in accordance with 
https://docs.oracle.com/javafx/2/api/javafx/scene/media/package-summary.html

supported extensions revised

---

Core/src/org/sleuthkit/autopsy/casemodule/Bundle.properties
Core/src/org/sleuthkit/autopsy/casemodule/Case.java
Core/src/org/sleuthkit/autopsy/casemodule/NewCaseVisualPanel1.java
Core/src/org/sleuthkit/autopsy/casemodule/NewCaseWizardAction.java
Core/src/org/sleuthkit/autopsy/core/UserPreferences.java
Core/src/org/sleuthkit/autopsy/corecomponents/MultiUserSettingsPanel.java

Read case type from the .aut file.

Add getCaseType(Path)

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryModule.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryOptionsPanel.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/PerCaseProperties.java

- replace ImageGalleryModule.MODULE_NAME with getter
- move drawable.db to ModuleOutput folder
- move per case ImageGallery properties to ModuleOutput folder.  cleanup PerCaseProperties.java

Move Image Gallery files to ModuleOutput folder

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/AddTagAction.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/CategorizeAction.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableDB.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/grouping/DrawableGroup.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/grouping/GroupKey.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/grouping/GroupManager.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/DrawableTile.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/GroupPane.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/SingleDrawableViewBase.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/navpanel/GroupTreeCell.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/navpanel/NavPanel.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/navpanel/TreeNodeComparators.java

- refactor GroupPane to have simpelr update mechanism
- refactor CategorizeAction to display progress and have more reliable performance
- fix bugs keeping directory tree in sync with Image Gallery
- cleanup

Group pane refactor and Categorization bugs

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/OnStart.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/navpanel/GroupTreeCell.java

fix NPE in GroupTreeCell by not removing null Listener

---

pythonExamples/fileIngestModule.py

Pycharm is making all that formatting change.
Added an example to query BB.
The example also shows the relation between AbstractFile/AbstractContent, BB Artifact, and BB Attributes

Added BB query sample PY code in the exsiting fileIngestModule.py

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/GroupPane.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/SingleDrawableViewBase.java

fix the fix for multiselect exceptions

prevent index out of bounds during multiselect

---

Core/nbproject/project.xml

To use AutopsyEvent in other applications

Export org.sleuthkit.autopsy.events 

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/Bundle.properties
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/HighlightedTextMarkup.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/LuceneQuery.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/Server.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/SolrSearchService.java

Modified Server.openCore() to check Solr server connectivity.

Moved Solr query outside for loop in LuceneQuery.performLuceneQuery().

---

Core/src/org/sleuthkit/autopsy/corecomponents/DataResultPanel.java

Tabs are set up only once, same as before.

Result count is updated whenever children are added or removed

---

Core/src/org/sleuthkit/autopsy/core/ServicesMonitor.java
Core/src/org/sleuthkit/autopsy/ingest/IngestManager.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/SolrSearchService.java

* additional input checks for KWS
* exception handling

Case type verification in ingest manager

---

Core/src/org/sleuthkit/autopsy/modules/photoreccarver/Bundle.properties
Core/src/org/sleuthkit/autopsy/modules/photoreccarver/PhotoRecCarverFileIngestModule.java

Reverted the log message strings which were externalized to the resource bundle.

Photorec inbox message

---

Core/src/org/sleuthkit/autopsy/datamodel/Tags.java

I don't know how this relates to all the work going on in collaborative, but this is a bug in develop.

update the artifact tag  nodes when tags are created/deleted

---

nbproject/platform.properties

Reverts sleuthkit/autopsy#1528

Revert "removing jellybeans from disabled modules"

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java

add missing closing parenthesis

fix broken SQL query.

---

ImageGallery/nbproject/project.xml
ImageGallery/nbproject/suite.properties
nbproject/project.properties

Reverts sleuthkit/autopsy#1539

Revert "turn on IG"

---

Core/src/org/sleuthkit/autopsy/modules/embeddedfileextractor/SevenZipExtractor.java

Small change for more readability.

adding underscore between file name and item index

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/navpanel/GroupTreeItem.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/navpanel/NavPanel.java

- rework NavPanel threading
- simplify logic
- ensure setFocusedGroup always called from javafx thread.

review NavPanel threading

---

Core/src/org/sleuthkit/autopsy/modules/hashdatabase/HashDbIngestModule.java

We could add the totals when we create the job (at refCounter), but since these will have 0 anyways, we can just use getTotalsForIngestJobs() when in postSummary which would create one if it doesn't exists anyways.

Hashdb null pointer

---

Core/src/org/sleuthkit/autopsy/modules/embeddedfileextractor/SevenZipExtractor.java

This fixes the missing paths from tsk_files_path

uncomment path initialization code

---

Core/src/org/sleuthkit/autopsy/timeline/FXMLConstructor.java
Core/src/org/sleuthkit/autopsy/timeline/datamodel/eventtype/MiscTypes.java
Core/src/org/sleuthkit/autopsy/timeline/explorernodes/EventNode.java

plus minor cleanup and comment improvements

replace Exception.printStackTrace with proper logging

---

Core/src/org/sleuthkit/autopsy/corecomponents/DataResultPanel.java

Reverts sleuthkit/autopsy#1585

Revert "Data result panel fix"

---

docs/doxygen/modDevPython.dox

Reverts sleuthkit/autopsy#1521

Revert "adding documentations to how to install jython editions"

---

ImageGallery/nbproject/project.xml
ImageGallery/nbproject/suite.properties
nbproject/project.properties

Reverts sleuthkit/autopsy#1621

Revert "enable ImageGallery"

---

ImageGallery/nbproject/project.xml
ImageGallery/nbproject/suite.properties
nbproject/project.properties

Reverts sleuthkit/autopsy#1622

Revert "Revert "enable ImageGallery""

---

Core/src/org/sleuthkit/autopsy/core/layer.xml

A small change, but took a while to figure out...

remove appearance from options

---

Core/src/org/sleuthkit/autopsy/casemodule/Bundle.properties
Core/src/org/sleuthkit/autopsy/casemodule/Bundle_ja.properties
Core/src/org/sleuthkit/autopsy/casemodule/NewCaseVisualPanel1.form
Core/src/org/sleuthkit/autopsy/casemodule/NewCaseVisualPanel1.java

New case wizard layout changes for case type

---

Core/src/org/sleuthkit/autopsy/timeline/datamodel/EventBundle.java
Core/src/org/sleuthkit/autopsy/timeline/datamodel/EventCluster.java
Core/src/org/sleuthkit/autopsy/timeline/datamodel/EventStripe.java
Core/src/org/sleuthkit/autopsy/timeline/datamodel/eventtype/ArtifactEventType.java
Core/src/org/sleuthkit/autopsy/timeline/datamodel/eventtype/WebTypes.java
Core/src/org/sleuthkit/autopsy/timeline/db/EventDB.java
Core/src/org/sleuthkit/autopsy/timeline/db/EventsRepository.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/DetailViewPane.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventBundleNodeBase.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventClusterNode.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventDetailsChart.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventStripeNode.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/EventDescriptionTreeItem.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/EventTypeTreeItem.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/EventsTree.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/NavTreeItem.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/RootItem.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/TreeComparator.java

this pull request reinstates the new sub cluster expanion UI with performance improvements.

Subcluster expansion 2

---

Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/DetailViewPane.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventDetailsChart.java

simplify scroll speed management, and scroll bounds WIP, cleanup
cleanup and comments

fix scroll speed management

---

Core/src/org/sleuthkit/autopsy/timeline/ui/AbstractVisualizationPane.java
Core/src/org/sleuthkit/autopsy/timeline/ui/countsview/CountsViewPane.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/Bundle.properties
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventBundleNodeBase.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventDetailsChart.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventsDetailsChart.css
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/GuideLine.java

fix guideline tooltip and cleanup/refactor related code

Tl guideline tooltip

---

Core/src/org/sleuthkit/autopsy/timeline/actions/Back.java
Core/src/org/sleuthkit/autopsy/timeline/actions/Bundle.properties
Core/src/org/sleuthkit/autopsy/timeline/actions/Forward.java
Core/src/org/sleuthkit/autopsy/timeline/actions/ResetFilters.java
Core/src/org/sleuthkit/autopsy/timeline/ui/NoEventsDialog.fxml
Core/src/org/sleuthkit/autopsy/timeline/ui/VisualizationPanel.java

adjust layout of no events dialog
move strings from Bundle.properties to NbBundle.Messages annotations

add "back" to actions available form no events dialog

---

Core/src/org/sleuthkit/autopsy/events/AutopsyEventPublisher.java

Add multiple retries to remote event publishing

---

Core/src/org/sleuthkit/autopsy/timeline/datamodel/FilteredEventsModel.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventBundleNodeBase.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventClusterNode.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventDetailsChart.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventStripeNode.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/EventDescriptionTreeItem.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/EventTypeTreeItem.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/EventsTree.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/RootItem.java

- further performance improvements by only creating actions and buttons as need on mouseover.
- small bug fixes
- cleanup

Tl lazy action creation

---

Core/src/org/sleuthkit/autopsy/timeline/datamodel/EventBundle.java
Core/src/org/sleuthkit/autopsy/timeline/datamodel/EventCluster.java
Core/src/org/sleuthkit/autopsy/timeline/datamodel/EventStripe.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventBundleNodeBase.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventClusterNode.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventDetailsChart.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/EventStripeNode.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/EventDescriptionTreeItem.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/EventTypeTreeItem.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/EventsTree.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/NavTreeItem.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/tree/RootItem.java

don't resort the tree so often, and other small optimizations and fixes

Tl sorting optimization

---

Core/src/org/sleuthkit/autopsy/datamodel/ExtractedContent.java
test/script/regression.py

Looks like Jenkins uses this to figure out failures

Change error code

---

Core/src/org/sleuthkit/autopsy/corecomponents/MediaViewImagePanel.css
Core/src/org/sleuthkit/autopsy/corecomponents/MediaViewImagePanel.java
Core/src/org/sleuthkit/autopsy/coreutils/ImageUtils.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/FileTypeUtils.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/DrawableTileBase.java

after https://github.com/sleuthkit/autopsy/pull/1773

Read aniamted gifs

---

Core/src/org/sleuthkit/autopsy/modules/filetypeid/FileTypeDetector.java

Logged the error instead of throwing the exception.

---

Core/src/org/sleuthkit/autopsy/ingest/ModuleDataEvent.java

This is where I added back getArtifactType in ModuleDataEvent

Custom artifact addition change revision

---

Core/src/org/sleuthkit/autopsy/datamodel/ExtractedContent.java

AUT-1848 code, to be reviewed.

Custom artifact addition 1848.2

---

Core/src/org/sleuthkit/autopsy/modules/UserArtifacts/Bundle.properties
Core/src/org/sleuthkit/autopsy/modules/UserArtifacts/UserArtifactIngestModule.java
Core/src/org/sleuthkit/autopsy/modules/UserArtifacts/UserArtifactIngestModuleFactory.java

Module for making new custom artifacts

Custom artifact addition 1851

---

Core/src/org/sleuthkit/autopsy/modules/UserArtifacts/UserArtifactIngestModule.java

Changed attribute type on ingest module

---

Core/src/org/sleuthkit/autopsy/directorytree/DirectoryTreeTopComponent.java
Core/src/org/sleuthkit/autopsy/modules/UserArtifacts/UserArtifactIngestModule.java

Custom artifact addition fixed DirectoryTreeTopComponent.viewArtifact

---

Core/src/org/sleuthkit/autopsy/casemodule/AddImageTask.java
Core/src/org/sleuthkit/autopsy/casemodule/ImageDSProcessor.java
Core/src/org/sleuthkit/autopsy/casemodule/LocalDiskDSProcessor.java

An ASCII-printable identifier for the data source that is unique across multiple cases (e.g., a UUID).

Next steps for data source id feature

---

Core/src/org/sleuthkit/autopsy/coreutils/Bundle.properties
Core/src/org/sleuthkit/autopsy/coreutils/FileUtil.java
Core/src/org/sleuthkit/autopsy/coreutils/ImageUtils.java
Core/src/org/sleuthkit/autopsy/coreutils/NetworkUtils.java
Core/src/org/sleuthkit/autopsy/coreutils/PlatformUtil.java
Core/src/org/sleuthkit/autopsy/coreutils/UNCPathUtilities.java
Core/src/org/sleuthkit/autopsy/coreutils/VideoUtils.java

This was another case where @Messages() was used by the developer instead of the proper Bundle.properties file. Again, it may be something that NetBeans is auto-generating.

1501 ja core coreutils

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java

Reverts sleuthkit/autopsy#1876

Revert "1501 ja image gallery - redo 2"

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/DrawableTile.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/DrawableTileBase.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/GroupPane.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/SlideShowView.fxml
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/SlideShowView.java

restrict double click action on SlideShowView to non control areas

---

Core/src/org/sleuthkit/autopsy/corecomponents/MultiUserSettingsPanel.form
Core/src/org/sleuthkit/autopsy/corecomponents/MultiUserSettingsPanel.java

converted fonts to be derivative.

core components - derivative fonts

---

Core/src/org/sleuthkit/autopsy/directorytree/FileSystemDetailsPanel.form
Core/src/org/sleuthkit/autopsy/directorytree/FileSystemDetailsPanel.java
Core/src/org/sleuthkit/autopsy/directorytree/ImageDetailsPanel.form
Core/src/org/sleuthkit/autopsy/directorytree/ImageDetailsPanel.java
Core/src/org/sleuthkit/autopsy/directorytree/VolumeDetailsPanel.form
Core/src/org/sleuthkit/autopsy/directorytree/VolumeDetailsPanel.java

converted UI fonts to derived fonts

core dir tree - converted to derived fonts in UI

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/DropdownListSearchPanel.form
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/DropdownListSearchPanel.java

The Exception seems to indicate that .getFont() was returning NULL. This change makes the jSplitPane1 get the font from leftPane, which will have a valid font.

fix NullPointerException due to null getFont().

---

Core/src/org/sleuthkit/autopsy/casemodule/AddImageTask.java
Core/src/org/sleuthkit/autopsy/casemodule/AddImageWizardChooseDataSourceVisual.java
Core/src/org/sleuthkit/autopsy/casemodule/AddImageWizardIngestConfigPanel.java
Core/src/org/sleuthkit/autopsy/casemodule/AddLocalFilesTask.java
Core/src/org/sleuthkit/autopsy/casemodule/ImageDSProcessor.java
Core/src/org/sleuthkit/autopsy/casemodule/ImageFilePanel.java
Core/src/org/sleuthkit/autopsy/casemodule/LocalDiskDSProcessor.java
Core/src/org/sleuthkit/autopsy/casemodule/LocalFilesDSProcessor.java
Core/src/org/sleuthkit/autopsy/corecomponentinterfaces/DataSourceProcessor.java
Core/src/org/sleuthkit/autopsy/corecomponentinterfaces/DataSourceProcessorCallback.java
branding/core/core.jar/org/netbeans/core/startup/Bundle.properties
branding/modules/org-netbeans-core-windows.jar/org/netbeans/core/windows/view/ui/Bundle.properties

Update DSP docs, make AddImageTask thread-safe, DSPs always callback.

Data source processing fixes

---

Core/src/org/sleuthkit/autopsy/modules/interestingitems/FilesSet.java
Core/src/org/sleuthkit/autopsy/modules/interestingitems/FilesSetRulePanel.java

Fixed file size condition limitation on 0 case 

---

Core/src/org/sleuthkit/autopsy/timeline/zooming/ZoomSettingsPane.java

fix bug accidentaly introduced in ZoomSettingsPane refactoring

TL Fix back action

---

Core/src/org/sleuthkit/autopsy/modules/filetypeid/FileTypeIdGlobalSettingsPanel.form
Core/src/org/sleuthkit/autopsy/modules/filetypeid/FileTypeIdGlobalSettingsPanel.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/KeywordSearchGlobalSettingsPanel.form
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/KeywordSearchGlobalSettingsPanel.java

Fixed global settings panels' ui

---

Core/src/org/sleuthkit/autopsy/modules/filetypeid/FileTypeIdGlobalSettingsPanel.form
Core/src/org/sleuthkit/autopsy/modules/filetypeid/FileTypeIdGlobalSettingsPanel.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/KeywordSearchGlobalSettingsPanel.form
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/KeywordSearchGlobalSettingsPanel.java

Reverts sleuthkit/autopsy#2113

Revert "Fixed global settings panels' ui"

---

Core/src/org/sleuthkit/autopsy/timeline/ui/IntervalSelector.java
Core/src/org/sleuthkit/autopsy/timeline/ui/TimeLineChart.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/DetailsChart.java

keep pinned toggle in sync with state of visualization.  

---

Core/src/org/sleuthkit/autopsy/casemodule/CueBannerPanel.java

Bug fix where one of CueBannerPanel's constructors was not fetching latest data and not updating the panel properly

1680 CueBannerPanel bug fix 

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/grouping/GroupManager.java

Eliminates null pointer exceptions when closing a case while re-categorizing by doing a null check on the DB

2142 case closing2

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/LuceneQuery.java

fix npe by using much simpler implementation to filter out hits inside the window, that also works for hits that are not single terms in the Solr index.

drop Term Vector Component

---

Core/src/org/sleuthkit/autopsy/filesearch/DateSearchFilter.java

fix copy-paste error at setting setting the createdChecked variable

fix copy-paste error

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/TermsComponentQuery.java

2281- change the solr field that TermsComponentQuery searches on from content_ws to text.

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/KeywordSearch.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/KeywordSearchQuery.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/LuceneQuery.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/QueryResults.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/RegexQuery.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/TermsComponentQuery.java

Depends on https://github.com/sleuthkit/sleuthkit/pull/765

Add document ids and search type to keyword hit artifacts

---

Core/src/org/sleuthkit/autopsy/datamodel/ArtifactStringContent.java
Core/src/org/sleuthkit/autopsy/test/CustomArtifactsCreatorIngestModuleFactory.java

The Autopsy source code in the "search_improvements" branch wasn't building

Fixed build errors

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/QueryResults.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/RegexQuery.java

allways pull back content so that regex searches work even when previews are turned off. allways make a snippet for regex searches since we have the content anyways.
comes after PR #2532

2163 ccn snippets

---

Core/src/org/sleuthkit/autopsy/actions/AddBlackboardArtifactTagAction.java

Update copyright AddBlackboardArtifactTagAction

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/Chrome.java
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/Extract.java
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractIE.java
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/Firefox.java
branding/core/core.jar/org/netbeans/core/startup/Bundle.properties
branding/modules/org-netbeans-core-windows.jar/org/netbeans/core/windows/view/ui/Bundle.properties
nbproject/genfiles.properties

Attach generated blackboard artifacts to the generated ModuleDataEvents for TSK_WEB_BOOKMARK, TSK_WEB_COOKIE, TSK_WEB_DOWNLOAD, and TSK_WEB_HISTORY artifact types fired from the RecentActivity module.

Update RecentActivity NBM to attach artifacts to ModuleDataEvents

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/LuceneQuery.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/RegexQuery.java

replace broken paging with cursor based paging

---

Core/src/org/sleuthkit/autopsy/ingest/runIngestModuleWizard/IngestProfileSelectionPanel.java

Center align label text w.r.t to button.

VIK-2502: Change radio buttons to toggle buttons for picking profile

---

Core/src/org/sleuthkit/autopsy/casemodule/Bundle.properties
Core/src/org/sleuthkit/autopsy/casemodule/Bundle_ja.properties

Resubmitting pull request, this time for 'rc-280'.

Fixed parsing issue in case name validation error.

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/HtmlTextExtractor.java

Minor update to fix the 'static' warning message.

Fixed 'static' reference.

---

Core/src/org/sleuthkit/autopsy/datamodel/HashsetHits.java
Core/src/org/sleuthkit/autopsy/datamodel/InterestingHits.java
Core/src/org/sleuthkit/autopsy/datamodel/KeywordHits.java
Core/src/org/sleuthkit/autopsy/timeline/explorernodes/EventRootNode.java

Fixed the InterestingHits nodes not showing up in the table sporadically.

2536: Review ChildFactory uses for long-running tasks

---

Core/src/org/sleuthkit/autopsy/corecomponents/DataResultViewerTable.java

persist the column sorting info plus some minor cleanup

2210 persist sort

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java

This is needed for CE project.

create artifacts for USB devices as a ModuleDataEvent.

---

Experimental/src/org/sleuthkit/autopsy/experimental/enterpriseartifactmanager/datamodel/PostgresEamDb.java
Experimental/src/org/sleuthkit/autopsy/experimental/enterpriseartifactmanager/datamodel/SqliteEamDb.java

in both Postgres and SQLite db schema's, changed field type from 'character varying(NN)' to 'text'

resolve exceptions due to db field varying length too short

---

Core/src/org/sleuthkit/autopsy/corecomponents/DataContentViewerArtifact.java

Fixes display of Value fields with multi-line content in the Results Content Viewer.  Value fields with extremely long single line content will still need the user to adjust column widths and possibly copy out the cell contents and paste them into a text editor.

2780 multi line support for Results Content Viewer table

---

CentralRepository/src/org/sleuthkit/autopsy/centralrepository/contentviewer/DataContentViewerOtherCasesTableCellRenderer.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/contentviewer/DataContentViewerOtherCasesTableModel.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/AbstractSqlEamDb.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/EamArtifactInstance.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/EamArtifactUtil.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/EamGlobalFileInstance.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/CaseEventListener.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/ingestmodule/IngestModule.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/optionspanel/ImportHashDatabaseDialog.java

Also changed the case of the known status value in the content viewer to be lower case. It now uses the exact getName() text from the Tsk FileKnown Enum.

Replace Known_Status Enum with Tsk FileKnown Enum

---

CentralRepository/src/org/sleuthkit/autopsy/centralrepository/contentviewer/DataContentViewerOtherCases.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/AbstractSqlEamDb.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/EamArtifact.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/EamArtifactInstance.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/EamCase.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/EamDb.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/EamDbUtil.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/EamGlobalFileInstance.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/PostgresEamDb.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/PostgresEamDbSettings.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/SqliteEamDb.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/SqliteEamDbSettings.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/BadFileTagRunner.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/CaseEventListener.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/IngestEventsListener.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/NewArtifactsRunner.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/ingestmodule/IngestModule.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/optionspanel/EamDbSettingsDialog.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/optionspanel/ImportHashDatabaseDialog.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/optionspanel/ManageCorrelationPropertiesDialog.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/optionspanel/ManageTagsDialog.form
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/optionspanel/ManageTagsDialog.java

This work is based off of the release-4.4.1 branch, but I'm submitting this PR to the develop branch per @rcordovano 's direction.
- updated db schema to allow some values to be NULL, and force others to be NOT NULL
- updated code to allow null values in objects and handle null values read from db.
- added character validation to correlation type db table names.

Schema changes2

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/CategorizeAction.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/NextUnseenGroup.java

- convert Worker thread to an Executor
- some other related cleanup

2643 block until ig is shutdown

---

Core/src/org/sleuthkit/autopsy/datamodel/FileTypesByMimeType.java

also filter know files from mime type tree ( count and actual results shown) when selected by user.

clean up FileTypesByMimeType

---

Core/src/org/sleuthkit/autopsy/directorytree/ExtractUnallocAction.java
Core/src/org/sleuthkit/autopsy/ingest/GetFilesCountVisitor.java
Core/src/org/sleuthkit/autopsy/modules/interestingitems/FilesSet.java

Add support for new TSK_FS_META_TYPE_VIRT_DIR

---

CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/AbstractSqlEamDb.java
CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/EamArtifactUtil.java

Don't make artifacts for short phone numbers.

Don't save blank entries to the database.

---

Core/src/org/sleuthkit/autopsy/ingest/IngestMonitor.java

Logging disk space for debug purposes only

Disabled disk space usage check (2903)

---

Core/src/org/sleuthkit/autopsy/datamodel/FileTypesByExtension.java

requires a case created/upgraded with https://github.com/sleuthkit/sleuthkit/pull/885

use extension column in query

---

Core/src/org/sleuthkit/autopsy/casemodule/services/FileManager.java
Core/src/org/sleuthkit/autopsy/datamodel/AbstractContentChildren.java
Core/src/org/sleuthkit/autopsy/datamodel/AbstractContentNode.java
Core/src/org/sleuthkit/autopsy/datamodel/BlackboardArtifactNode.java
Core/src/org/sleuthkit/autopsy/datamodel/ContentNodeVisitor.java
Core/src/org/sleuthkit/autopsy/datamodel/EmailExtracted.java
Core/src/org/sleuthkit/autopsy/directorytree/DataResultFilterNode.java
Core/src/org/sleuthkit/autopsy/directorytree/DirectoryTreeFilterChildren.java
Core/src/org/sleuthkit/autopsy/directorytree/DirectoryTreeFilterNode.java
thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/ThunderbirdMboxFileIngestModule.java

2692: Messages & Attachments show in DataSource tree

2841: Attachments are children of messages.

---

Testing/src/org/sleuthkit/autopsy/testing/AutopsyTestCases.java

Tested couple of timeout settings, this setting works locally and hope it works for nightly too.

2682: reset the Jemmy tools timeout number to get longer time

---

Core/src/org/sleuthkit/autopsy/centralrepository/optionspanel/EamDbSettingsDialog.java
Core/src/org/sleuthkit/autopsy/centralrepository/optionspanel/GlobalSettingsPanel.form
Core/src/org/sleuthkit/autopsy/centralrepository/optionspanel/GlobalSettingsPanel.java

an un-configured central repo with the checkbox to use one checked is no longer a valid configuration.

2970 fix central repo options panel

---

Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/PostgresEamDbSettings.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/SqliteEamDbSettings.java

Force organization name to be unique.

Force hash set name/version combination to be unique.

---

Core/src/org/sleuthkit/autopsy/ingest/runIngestModuleWizard/RunIngestModulesAction.java

to abstractAction to avoid exeption

3061 changed runIngestmodules from callableSystemAction 

---

Core/src/org/sleuthkit/autopsy/timeline/TimeLineTopComponent.java

wrap EventRootNode in a TableFilterNode before pushing it to result viewer.

3008 fix class cast error from timeline

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/grouping/DrawableGroup.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/grouping/GroupManager.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/grouping/GroupSortBy.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/Toolbar.java

set initial group sorting to Priority  and the initialize toolbar with GroupSortBy from GroupManager

864 prioritization

---

Core/src/org/sleuthkit/autopsy/communications/CVTTopComponent.java

the content of this method moved to FiltersPanel

remove unused method

---

Core/src/org/sleuthkit/autopsy/communications/CVTTopComponent.java
Core/src/org/sleuthkit/autopsy/communications/FiltersPanel.java

plus comments and some minor cleanup

update and apply the filters when the CVT window is (re)opened

---

Experimental/src/org/sleuthkit/autopsy/experimental/autoingest/AutoIngestManager.java

I have verified that this also takes care of VIK-3160.

2942 crashed jobs

---

Core/nbproject/project.xml
Core/src/org/sleuthkit/autopsy/casemodule/services/TagNameDefiniton.java
Core/src/org/sleuthkit/autopsy/datamodel/DhsImageCategory.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/CategorizeAction.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/CategorizeGroupAction.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/CategorizeSelectedFilesAction.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/CategoryManager.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableAttribute.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableDB.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableFile.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableTagsManager.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/grouping/GroupManager.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/SummaryTablePane.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/Toolbar.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/DrawableView.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/GroupPane.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/MetaDataPane.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/SlideShowView.java

Requires PR https://github.com/sleuthkit/sleuthkit/pull/1015 for Sleuthkit

3199 consolidate default tags

---

Core/src/org/sleuthkit/autopsy/communications/AccountsRootChildren.java
Core/src/org/sleuthkit/autopsy/communications/FiltersPanel.java
Core/src/org/sleuthkit/autopsy/communications/MessageBrowser.java

update to getTypeSpecificID

---

Core/src/org/sleuthkit/autopsy/communications/AccountsRootChildren.java
Core/src/org/sleuthkit/autopsy/communications/FiltersPanel.form
Core/src/org/sleuthkit/autopsy/communications/FiltersPanel.java
InternalPythonModules/android/calllog.py
InternalPythonModules/android/contact.py
InternalPythonModules/android/textmessage.py
InternalPythonModules/android/wwfmessage.py

use the name of the first data source for a device as the "display name " of the device.
also include the fix from PR 3252

883 user friendly device ids

---

Core/src/org/sleuthkit/autopsy/contentviewers/MessageContentViewer.java

depends on TSK PR https://github.com/sleuthkit/sleuthkit/pull/1044

890 enable message content viewer in more places

---

Core/src/org/sleuthkit/autopsy/casemodule/Case.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/EamGlobalSet.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/SqliteEamDb.java
docs/doxygen-user/adHocKeywordSearch.dox
thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/ThunderbirdMboxFileIngestModule.java

Cleaned up some doxygen warnings.

Improved regex documentation.

---

Core/src/org/sleuthkit/autopsy/directorytree/ExtractUnallocAction.java

Renamed many ambiguous variables.

Added locks around the lists of images/volumes in progress.

---

Core/src/org/sleuthkit/autopsy/datamodel/ExtractedContent.java
Core/src/org/sleuthkit/autopsy/modules/encryptiondetection/EncryptionDetectionFileIngestModule.java
Core/src/org/sleuthkit/autopsy/report/ReportHTML.java
Core/src/org/sleuthkit/autopsy/report/TableReportGenerator.java

Requires Sleuthkit PR https://github.com/sleuthkit/sleuthkit/pull/1045

3329 Use TSK_ENCRYPTION_SUSPECTED artifact for Encryption module

---

Core/src/org/sleuthkit/autopsy/casemodule/MultiUserCasesPanel.java

Make double click open  multi-user case action perform the same as Open Case button

3350 move call to openCase when double clicking off EDT

---

Core/src/org/sleuthkit/autopsy/communications/Bundle.properties
Core/src/org/sleuthkit/autopsy/communications/FiltersPanel.form
Core/src/org/sleuthkit/autopsy/communications/FiltersPanel.java

- Added a message to explicitly indicate that a refresh is needed.

933: Browse Msgs Column and Results count can get out of sync

---

Core/src/org/sleuthkit/autopsy/corecomponents/MediaViewVideoPanel.java
Core/src/org/sleuthkit/autopsy/coreutils/ImageUtils.java
Core/src/org/sleuthkit/autopsy/modules/embeddedfileextractor/MSOfficeEmbeddedContentExtractor.java
Core/src/org/sleuthkit/autopsy/modules/embeddedfileextractor/SevenZipExtractor.java
Core/src/org/sleuthkit/autopsy/modules/encryptiondetection/EncryptionDetectionFileIngestModule.java
Core/src/org/sleuthkit/autopsy/modules/exif/ExifParserFileIngestModule.java
Core/src/org/sleuthkit/autopsy/modules/fileextmismatch/FileExtMismatchIngestModule.java
Core/src/org/sleuthkit/autopsy/modules/filetypeid/FileTypeDetector.java
Core/src/org/sleuthkit/autopsy/modules/filetypeid/FileTypeIdIngestModule.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/FileTypeUtils.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/KeywordSearchIngestModule.java
branding/core/core.jar/org/netbeans/core/startup/Bundle.properties
branding/modules/org-netbeans-core-windows.jar/org/netbeans/core/windows/view/ui/Bundle.properties

Makes single type detection API that has no side effects and does not throw, simplifying a confusing and complex API.

File detector API changes

---

ImageGallery/nbproject/platform.properties
ScalpelCarver/nbproject/platform.properties
nbproject/platform.properties

changed defunct netbeans url (deadlock.netbeans.*) to the current url

---

Core/build.xml
Core/src/org/sleuthkit/autopsy/casemodule/AddImageWizardSelectDspVisual.java
Core/src/org/sleuthkit/autopsy/casemodule/Case.java
Core/src/org/sleuthkit/autopsy/datasourceprocessors/AddMemoryImageTask.java
Core/src/org/sleuthkit/autopsy/datasourceprocessors/Bundle.properties
Core/src/org/sleuthkit/autopsy/datasourceprocessors/MemoryDSInputPanel.form
Core/src/org/sleuthkit/autopsy/datasourceprocessors/MemoryDSInputPanel.java
Core/src/org/sleuthkit/autopsy/datasourceprocessors/MemoryDSProcessor.java
Core/src/org/sleuthkit/autopsy/datasourceprocessors/VolatilityProcessor.java
Core/src/org/sleuthkit/autopsy/directorytree/ExternalViewerAction.java
branding/core/core.jar/org/netbeans/core/startup/Bundle.properties
branding/modules/org-netbeans-core-windows.jar/org/netbeans/core/windows/view/ui/Bundle.properties
thirdparty/Volatility/AUTHORS-2.5.txt
thirdparty/Volatility/AUTHORS-2.6.txt
thirdparty/Volatility/CREDITS-2.5.txt
thirdparty/Volatility/CREDITS-2.6.txt
thirdparty/Volatility/LEGAL-2.5.txt
thirdparty/Volatility/LEGAL2.6.txt
thirdparty/Volatility/LICENSE-2.5.txt
thirdparty/Volatility/LICENSE2.6.txt
thirdparty/Volatility/README-2.5.txt
thirdparty/Volatility/README2.6.txt

Volatility module

---

Core/src/org/sleuthkit/autopsy/datasourceprocessors/VolatilityProcessor.java

Added checks to get better results in dlllist, cmdline and handles

Added checks for better results in plugins

---

Core/src/org/sleuthkit/autopsy/contentviewers/SQLiteViewer.java

Add check for temp db existing before making a copy.
Don't delete temp db

Put all SQLite content viewer processing on the EDT.

---

Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/AbstractSqlEamDb.java

Made newCase() method synchronized, added a check for existing database

Fix for a race condition in Correlation Engine

---

Experimental/src/org/sleuthkit/autopsy/experimental/volatilityDSP/AddMemoryImageTask.java
Experimental/src/org/sleuthkit/autopsy/experimental/volatilityDSP/MemoryDSInputPanel.java
Experimental/src/org/sleuthkit/autopsy/experimental/volatilityDSP/MemoryDSProcessor.java
Experimental/src/org/sleuthkit/autopsy/experimental/volatilityDSP/VolatilityProcessor.java

- Bug fixes
- Clean up
- Improved error handling

Volatility fixes

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/AdHocQueryRequest.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/AdHocSearchChildFactory.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/AdHocSearchDelegator.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/AdHocSearchFilterNode.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/AdHocSearchPanel.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/DropdownListSearchPanel.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/DropdownSingleTermSearchPanel.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/ExtractedContentViewer.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/IngestSearchRunner.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/KeywordSearchIngestModule.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/SolrSearchService.java

renamed classes - 3503

---

Core/src/org/sleuthkit/autopsy/commonfilesearch/CommonFilesMetadataBuilder.java

This solves the problem Ben encountered while testing the common files feature with the big data set.

Fix for postgres String handling of mime_type query

---

Core/src/org/sleuthkit/autopsy/directorytree/DirectoryTreeTopComponent.java

added if-else logic to manually respond to the selection if the
node remains the same in the tree view.

added logic to respond for selection in DirectoryTreeComponent.viewArtifact

---

Core/src/org/sleuthkit/autopsy/commonfilesearch/CommonFilesSearchResultsViewerTable.java
Core/src/org/sleuthkit/autopsy/datamodel/InstanceCountNode.java

some ui tweaks

---

Core/src/org/sleuthkit/autopsy/centralrepository/optionspanel/ShowCasesDialog.form
Core/src/org/sleuthkit/autopsy/centralrepository/optionspanel/ShowCasesDialog.java

Changes the case information table to be re-sizeable and enlarges the default dialog size.

Allow resizing of table elements, make dialog default size larger.

---

Core/src/org/sleuthkit/autopsy/directorytree/DirectoryTreeTopComponent.java

Don't try to rebuild the tree when there is no open case.

3977: NPE when downloading shared config

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/grouping/GroupManager.java

3994: Image gallery doesnt work for Postgres

---

Core/src/org/sleuthkit/autopsy/report/TableReportGenerator.java

Also do not make link to sections with no data in the KW hits report.

4006 Show ad hoc keyword hits in report.

---

Core/src/org/sleuthkit/autopsy/casemodule/SingleUserCaseConverter.java
Core/src/org/sleuthkit/autopsy/datamodel/BlackboardArtifactTagNode.java
Core/src/org/sleuthkit/autopsy/datamodel/ContentTagNode.java
Core/src/org/sleuthkit/autopsy/report/TableReportGenerator.java

Requires Sleutkit PR https://github.com/sleuthkit/sleuthkit/pull/1290

4040 Associate the user name of who created a tag with that tag

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/LuceneQuery.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/RegexQuery.java

Reverts sleuthkit/autopsy#4038

Revert "Accounting for associated artifact."

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/LuceneQuery.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/RegexQuery.java

Reverts sleuthkit/autopsy#3999

Revert "4067 prevent duplicate keyword hits"

---

Core/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/IngestEventsListener.java
Core/src/org/sleuthkit/autopsy/centralrepository/ingestmodule/IngestModule.java
Core/src/org/sleuthkit/autopsy/modules/exif/ExifParserFileIngestModule.java
Core/src/org/sleuthkit/autopsy/modules/fileextmismatch/FileExtMismatchIngestModule.java
Core/src/org/sleuthkit/autopsy/modules/filetypeid/FileTypeIdIngestModule.java
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/Extract.java
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractIE.java
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/SearchEngineURLQueryExtractor.java
thunderbirdparser/nbproject/project.xml
thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/ThunderbirdMboxFileIngestModule.java

 update ThunderbirdMboxFileIngestModule for postArtifacts and cleanup

---

Core/src/org/sleuthkit/autopsy/report/TableReportGenerator.java

Comment and Description column will now always be present and correctly populated for Interesting Files in the HTML and excel reports.

4165 fix interesting file report columns

---

Core/src/org/sleuthkit/autopsy/commonfilesearch/CommonAttributeSearchResults.java

This will have a merge conflict when Brian's 4121 goes in

4174 reduce count call in intercase

---

Core/src/org/sleuthkit/autopsy/commonfilesearch/AbstractCommonAttributeSearcher.java
Core/src/org/sleuthkit/autopsy/commonfilesearch/AllInterCaseCommonAttributeSearcher.java
Core/src/org/sleuthkit/autopsy/commonfilesearch/CentralRepoCommonAttributeInstance.java
Core/src/org/sleuthkit/autopsy/commonfilesearch/CommonAttributePanel.java
Core/src/org/sleuthkit/autopsy/commonfilesearch/InterCaseCommonAttributeSearcher.java
Core/src/org/sleuthkit/autopsy/commonfilesearch/InterCaseSearchResultsProcessor.java
Core/src/org/sleuthkit/autopsy/commonfilesearch/IntraCaseCommonAttributeSearcher.java
Core/src/org/sleuthkit/autopsy/commonfilesearch/SingleInterCaseCommonAttributeSearcher.java

Fix bug with common file parent path in the root directory.

Don't use the intracase data source list in intercase searches.

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java

- Only process 'real' files (not folders etc.) for Image gallery.

1049: Image gallery rebuild does not complete for some images.

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableDB.java

- Added escaping path string for path groups

1087: Error/Exception from ImageGallery in creating groups

---

Core/src/org/sleuthkit/autopsy/modules/embeddedfileextractor/MSOfficeEmbeddedContentExtractor.java

Fix EFE handling of container exceptions

---

Core/src/org/sleuthkit/autopsy/casemodule/LocalFilesDSProcessor.java
Experimental/src/org/sleuthkit/autopsy/experimental/autoingest/AddArchiveTask.java

Don't use the device ID for the name in the Local Files DSP.
Depends on TSK PR #1352

4312 Prepend the archive name to any images extracted in the archive DSP.

---

Core/src/org/sleuthkit/autopsy/casemodule/Case.java
Core/src/org/sleuthkit/autopsy/timeline/ui/detailview/datamodel/DetailsViewModel.java
Core/src/org/sleuthkit/autopsy/timeline/ui/listvew/datamodel/ListViewModel.java

escape TL SQL statements
comments and minor refactoring

1121 - escape TL SQL statements

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableAttribute.java
ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableDB.java

- don't create a group for null/empty value for the group key.

1138: Error marking empty string group seen

---

Core/src/org/sleuthkit/autopsy/centralrepository/ingestmodule/Bundle.properties

Adjust Text to meet jira feedback

4487 rename option to be Save items to the Central Repository

---

Core/src/org/sleuthkit/autopsy/casemodule/CasePropertiesPanel.java
Core/src/org/sleuthkit/autopsy/casemodule/NewCaseWizardAction.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/AbstractSqlEamDb.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/EamArtifactUtil.java
Core/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/CaseEventListener.java
Core/src/org/sleuthkit/autopsy/centralrepository/ingestmodule/CentralRepoIngestModule.java

now that CRs cant be changed with a case open

4556 remove unnecessary calls to EamDb.getInstance().newCase() 

---

Core/src/org/sleuthkit/autopsy/contentviewers/Metadata.java

4428 show acquisition details

---

Core/src/org/sleuthkit/autopsy/casemodule/NewCaseWizardAction.java

Add back new case creation in CR to NewCaseWizardAction for when it has not been created yet by CaseEventListener in the CurrentCaseTask

fix npe when using postgres CR and creating a new case

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/Firefox.java

- Fix Downloads query
- Fix history query

1173: Fix Firefox parser

---

Core/src/org/sleuthkit/autopsy/textextractors/TikaTextExtractor.java

Reverts sleuthkit/autopsy#4510

Revert "Optimization and Bug fix - Make Tika use AbstractFile mimetype instead of recomputing"

---

Testing/src/org/sleuthkit/autopsy/testing/AutopsyTestCases.java

Screenshot usage for testing modified to only perform a screen shot for first timeout instead of at set points in testing.

4708 only perform screen shot when test times out first time

---

Core/src/org/sleuthkit/autopsy/corecomponents/DataContentViewerHex.java
Core/src/org/sleuthkit/autopsy/corecomponents/DataContentViewerString.java

First commit has all functional changes, 2nd and 3rd commit are just cleanup.

3956 is supported for data content viewers

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/Bundle.properties-MERGED
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/Chrome.java
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ChromeCacheExtractor.java

Reverts sleuthkit/autopsy#4630

Revert "4841: RecentActivity not making progress on large image"

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/Bundle.properties-MERGED
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/Chrome.java
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ChromeCacheExtractor.java

Reverts sleuthkit/autopsy#4633

Revert "Revert "4841: RecentActivity not making progress on large image""

---

Core/src/org/sleuthkit/autopsy/texttranslation/ui/Bundle.properties
Core/src/org/sleuthkit/autopsy/texttranslation/ui/Bundle.properties-MERGED
Core/src/org/sleuthkit/autopsy/texttranslation/ui/TranslatedTextViewer.java
Core/src/org/sleuthkit/autopsy/texttranslation/ui/TranslationContentPanel.form
Core/src/org/sleuthkit/autopsy/texttranslation/ui/TranslationContentPanel.java

This PR caps original text extraction to 50KB. The warning limit was removed and will be added back next in JIRA-5094 with more specific limits per translation service (ex. for Bing Translator: "Up to the first 5KB text translated").

5122 hang in translation viewer

---

docs/doxygen-user/installSolr.dox

5049 Added section on choosing user for solr service.

---

Core/src/org/sleuthkit/autopsy/centralrepository/contentviewer/DataContentViewerOtherCases.java
Core/src/org/sleuthkit/autopsy/centralrepository/contentviewer/OtherOccurrencesDataSourcesTableModel.java
Core/src/org/sleuthkit/autopsy/centralrepository/contentviewer/OtherOccurrencesFilesTableModel.java

@APriestman made me aware of an edge case where nodes were added for current case as well as CR data

Fix additional deduping bug in other occurrences content viewer

---

Core/src/org/sleuthkit/autopsy/communications/relationships/MessagesChildNodeFactory.java
Core/src/org/sleuthkit/autopsy/communications/relationships/ThreadChildNodeFactory.java
Core/src/org/sleuthkit/autopsy/communications/relationships/ThreadNode.java

I forgot to rename the branch before I pushed so just ignore that branch name please.

1242, 1274, ans 1275 - Sorted threads and messages by time and added text subject.

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/RegexQuery.java

Change so it removes infinite loop with [A-Z]* regex KWS.

2426 Infinite loop in keyword search

---

Core/test/qa-functional/src/org/sleuthkit/autopsy/commonpropertiessearch/CommonAttributeSearchInterCaseTest.java
Core/test/qa-functional/src/org/sleuthkit/autopsy/commonpropertiessearch/IngestedWithHashAndFileTypeInterCaseTest.java

Richard would like to see new gold diffs caused by the Timeline merge in the nightly test before fixing these.

Comment out failing common properties test files

---

Core/src/org/sleuthkit/autopsy/report/PortableCaseReportModule.java
Core/src/org/sleuthkit/autopsy/report/caseuco/Bundle.properties-MERGED
Core/src/org/sleuthkit/autopsy/report/caseuco/CaseUcoFormatExporter.java

This PR has only been partially tested. The final interaction with the PortableCaseReportModule remains untested due to Jira-5425

5374 case uco portable case

---

Core/src/org/sleuthkit/autopsy/casemodule/CaseOpenAction.java
Core/src/org/sleuthkit/autopsy/report/PortableCaseReportModule.java
Core/src/org/sleuthkit/autopsy/report/caseuco/Bundle.properties-MERGED
Core/src/org/sleuthkit/autopsy/report/caseuco/CaseUcoFormatExporter.java
KeywordSearch/solr/solr/configsets/AutopsyConfig/conf/schema.xml
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/Server.java
test/script/tskdbdiff.py

Merging latest develop branch into elastic-computing branch

Merge develop

---

Core/src/org/sleuthkit/autopsy/casemodule/datasourcesummary/DataSourceBrowser.java
Core/src/org/sleuthkit/autopsy/casemodule/datasourcesummary/DataSourceInfoUtilities.java
Core/src/org/sleuthkit/autopsy/casemodule/datasourcesummary/DataSourceLabeledValueCallback.java
Core/src/org/sleuthkit/autopsy/casemodule/datasourcesummary/DataSourceSingleValueCallback.java
Core/src/org/sleuthkit/autopsy/casemodule/datasourcesummary/DataSourceSummary.java
Core/src/org/sleuthkit/autopsy/casemodule/datasourcesummary/DataSourceSummaryCountsPanel.form
Core/src/org/sleuthkit/autopsy/casemodule/datasourcesummary/DataSourceSummaryCountsPanel.java
Core/src/org/sleuthkit/autopsy/casemodule/datasourcesummary/DataSourceSummaryDetailsPanel.form
Core/src/org/sleuthkit/autopsy/casemodule/datasourcesummary/DataSourceSummaryDetailsPanel.java
Core/src/org/sleuthkit/autopsy/commandlineingest/CommandLineOptionProcessor.java
Core/src/org/sleuthkit/autopsy/commonpropertiessearch/CommonAttributeSearchResultRootNode.java
Core/src/org/sleuthkit/autopsy/commonpropertiessearch/CommonAttributesSearchResultsViewerTable.java
Core/src/org/sleuthkit/autopsy/communications/relationships/SelectionInfo.java
Core/src/org/sleuthkit/autopsy/contentviewers/HtmlPanel.java
Core/src/org/sleuthkit/autopsy/core/AutopsyOptionProcessor.java
Core/src/org/sleuthkit/autopsy/datamodel/BaseChildFactory.java
Core/src/org/sleuthkit/autopsy/report/PortableCaseInterestingItemsListPanel.java
Core/src/org/sleuthkit/autopsy/report/PortableCaseTagsListPanel.java
Core/src/org/sleuthkit/autopsy/textextractors/TikaTextExtractor.java
CoreLibs/src/org/sleuthkit/autopsy/corelibs/OpenCvLoader.java
Testing/src/org/sleuthkit/autopsy/testing/AutopsyTestCases.java
Testing/test/qa-functional/src/org/sleuthkit/autopsy/testing/RegressionTest.java

Change the logger class from using java.util.logging.Logger to org.sleuthkit.autopsy.coreutils.Logger where appropriate.

2427 incorrect logger class widely used

---

thirdparty/rr-full/plugins/shellbags.pl

Update Shellbag plugin to  newer version in regripper

Update Shellbag plugin to newer version

---

Experimental/src/org/sleuthkit/autopsy/experimental/textclassifier/TextClassifierTrainerReportModule.java
Experimental/src/org/sleuthkit/autopsy/experimental/textclassifier/TextClassifierUtils.java

PR to replace https://github.com/sleuthkit/autopsy/pull/5204 with merge conflicts resolved.

5493 no size limit

---

Core/src/org/sleuthkit/autopsy/report/ArtifactSelectionDialog.java

5539-html-excel-report-arrayindexoutofboundsexception

---

docs/doxygen/modIngest.dox
docs/doxygen/platformConcepts.dox

5347 Changed ingest module docs to use postArtifact().

---

InternalPythonModules/android/tangomessage.py
InternalPythonModules/android/viber.py

The PR also includes a fix for a typo in the viber analyzer

Tango Analyzer typo

---

thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/PstParser.java
thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/ThunderbirdMboxFileIngestModule.java

- also fixed a typo in a (private) method name.

5574: NPE in Thunderbird Mbox file ingest module.

---

Core/src/org/sleuthkit/autopsy/communications/CVTTopComponent.form
Core/src/org/sleuthkit/autopsy/communications/CVTTopComponent.java
Core/src/org/sleuthkit/autopsy/communications/FiltersPanel.form
Core/src/org/sleuthkit/autopsy/communications/FiltersPanel.java

Reverts sleuthkit/autopsy#5242

Revert "1356 - cleaned up cvt layout"

---

InternalPythonModules/android/fbmessenger.py

- Fixed SQL query for the contacts to correctly skip over users own account

5564: Confusing contacts associated with account

---

thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/ThunderbirdMboxFileIngestModule.java

Npe in email parser

---

InternalPythonModules/android/fbmessenger.py
InternalPythonModules/android/imo.py
InternalPythonModules/android/operabrowser.py
InternalPythonModules/android/sbrowser.py
InternalPythonModules/android/shareit.py
InternalPythonModules/android/xender.py
InternalPythonModules/android/zapya.py

- get rid Account.Address
- handle required attribute arguments.

5604: CommunicationArtifactsHelper changes

---

thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/EmailMessage.java
thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/ThunderbirdMboxFileIngestModule.java

Check threaded messageId if null and skip it if it is.  Format code also.

5681-npe-running-email-parser-against-tb-mailbox

---

Core/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/IngestEventsListener.java
Core/src/org/sleuthkit/autopsy/contentviewers/MediaPlayerPanel.java
Core/src/org/sleuthkit/autopsy/texttranslation/ui/TranslatedTextViewer.java
docs/doxygen/footer.html

Update copyright for API docs.

---

Core/src/org/sleuthkit/autopsy/casemodule/CaseMetadata.java

Add UTF-8 Encoding so it writes to the aut file correctly for non-latin characters.

3649-investigate-encoding-of-case-description

---

InternalPythonModules/android/fbmessenger.py

Add attachments from the database to the message

5765-Collect-attachments-for-FB-Messenger

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableDB.java

Reverts sleuthkit/autopsy#5431

Revert "Remove unused prepared statements from DrawableDB"

---

InternalPythonModules/android/textnow.py

Add attachment to message and remove attachment from message body

5768-collect-attachments-for-TextNow

---

Core/src/org/sleuthkit/autopsy/modules/plaso/PlasoIngestModule.java

Move code to check if datasource is image to process instead of starup and fail gracefully if it is not.

5679-Allow-Plaso-to-more-silently-fail-for-non-images

---

ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableDB.java

Change insert and replace to insert and update (upsert).

5831-Tags-are-disappearing-when-reopening-a-case

---

Core/src/org/sleuthkit/autopsy/modules/fileextmismatch/FileExtMismatchDetectorModuleSettings.java
Core/src/org/sleuthkit/autopsy/modules/fileextmismatch/mismatch_config.xml

Added Office Documents to mismatch config and checkType ONLY_MEDIA_AND_EXE.

5656-Extension-mismatch-not-being-detected-in-word-documents

---

thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/ThunderbirdMboxFileIngestModule.java

Fixed frivolous device accounts being created for each file running through the Email Parser ingest module.

5709: Email attachments.

---

Core/src/org/sleuthkit/autopsy/casemodule/Bundle.properties-MERGED
Core/src/org/sleuthkit/autopsy/casemodule/UnpackagePortableCaseProgressDialog.java

Update Message for unpack previously seen case

5601-warn-user-if-they-already-unpackaged-a-portable-case-message

---

Core/src/org/sleuthkit/autopsy/contentviewers/MediaPlayerPanel.java

Band-aid fix for the release until the root cause is better understood.

5888 Gstreamer crash on Windows

---

test/script/regression.py

This keeps the build script from exiting if the diffs do not pass.

5881 Streamline Gold Updates Part Two

---

InternalPythonModules/GPX_Module/GPX_Parser_Module.py
InternalPythonModules/GPX_Module/gpxpy/PKG-INFO
InternalPythonModules/GPX_Module/gpxpy/__init__.py
InternalPythonModules/GPX_Module/gpxpy/geo.py
InternalPythonModules/GPX_Module/gpxpy/gpx.py
InternalPythonModules/GPX_Module/gpxpy/gpxfield.py
InternalPythonModules/GPX_Module/gpxpy/gpxxml.py
InternalPythonModules/GPX_Module/gpxpy/parser.py
InternalPythonModules/GPX_Module/gpxpy/utils.py

GPX internal python module update for open source and geoartifacthelper

5966-open-source-GPX-module-and-update-how-it-makes-artifacts

---

InternalPythonModules/GPX_Module/GPX_Parser_Module.py

remove module text from module name.

remove-module-text-from-GPX-module-name

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRecycleBin.java

Add $RECYCLE.BIN as the directory to look for $I files.

5922-ExtractRecycleBin.parseIFile-makes-assumptions-about-size-of-data-read

---

Core/src/org/sleuthkit/autopsy/coreutils/AppSQLiteDB.java
InternalPythonModules/android/calllog.py
InternalPythonModules/android/contact.py

- Removed getConnectionMetadata() api and added columnExists() & tableExists()

5907: Update legacy modules

---

Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/CorrelationAttributeInstance.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/RdbmsCentralRepoFactory.java

6014: Create persona tables.

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/RecentDocumentsByLnk.java

Reverts sleuthkit/autopsy#5655

Revert "6074-Standardize-file-paths-in-recent-documents-to-match-format-that-is-stored-in-autopsy-database"

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/RecentDocumentsByLnk.java

Add back commits that were accidently removed in recent revert of 

---

InternalPythonModules/GPX_Module/GPX_Parser_Module.py

While  I was working on this file, I cleaned it up, improved logging, updated it to create TSK_GPS_ROUTE artifacts correctly, and fixed some bugs in the capturing of names and timestamps.

6105 GPX Parser module fixes for API changes, bugs

---

InternalPythonModules/android/browserlocation.py

Change GPS_Trackpoint to GPS_Bookmark

6043-browserlocation.py-uses-deprecated-TSK_GPS_TRACKPOINT

---

InternalPythonModules/android/cachelocation.py

Change GPS_TRACKPOINT to GPS_BOOKMARK.  Change how cache file is processed and read.

6042-CacheLocation.py-is-using-TSK_GPS_TRACKPOINT

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java

Change from 2 to 1 for end of substring

6202-ExtractRegistry-parseTrustrecordsMRUList-cuts-off-USERPROFILE

---

Core/src/org/sleuthkit/autopsy/contentviewers/contextviewer/ContextViewer.java

Check if attribute is null and if it is then append unknown message to usage context

6203-ContextViewer-NPE-issuea

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java

6209-Array-index-out-of-bounds-exception-from-MRU-parsing-in-Recent-Activity-module

---

Running_Linux_OSX.txt

Addresses https://github.com/sleuthkit/autopsy/issues/5734

Updated Linux instructions to use bellsoft-java8-full

---

InternalPythonModules/android/calllog.py
InternalPythonModules/android/general.py
InternalPythonModules/android/textnow.py
InternalPythonModules/android/whatsapp.py

Do not attempt to create account when we do not have a valid phone number or email address.

6219: TskCoreException thrown from normalizePhoneNum

---

README.txt

KNOWN_ISSUES.txt is not present in this repository. Remove the reference to it.

Removed reference to KNOWN_ISSUES.txt

---

Core/src/org/sleuthkit/autopsy/modules/hashdatabase/AddHashValuesToDatabaseProgressDialog.java

I relaxed the MD5 pattern a bit to allow additional text in each line.
Anything thats left after the 32 character hash gets trimmed and treated as a comment.

Added the possibility to include a comment when adding hashes to a hash set

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractSru.java

Check if file found before it is used to avoid NPE

6349-NPE-in-SRU-recent-activity

---

Core/src/org/sleuthkit/autopsy/casemodule/AddImageTaskCallback.java
Core/src/org/sleuthkit/autopsy/casemodule/DefaultAddImageTaskCallback.java
Core/src/org/sleuthkit/autopsy/casemodule/ImageDSProcessor.java
Core/src/org/sleuthkit/autopsy/casemodule/LocalDiskDSProcessor.java
Core/src/org/sleuthkit/autopsy/ingest/DataSourceIngestJob.java
Core/src/org/sleuthkit/autopsy/ingest/IngestJob.java
Core/src/org/sleuthkit/autopsy/ingest/IngestManager.java
Core/src/org/sleuthkit/autopsy/ingest/IngestProgressSnapshotPanel.java
Core/src/org/sleuthkit/autopsy/ingest/IngestProgressSnapshotProvider.java
Experimental/src/org/sleuthkit/autopsy/experimental/autoingest/AutoIngestJob.java
Experimental/src/org/sleuthkit/autopsy/experimental/autoingest/AutoIngestJobsNode.java

Make AddImageTaskCallback an interface.

Move Snapshot class.

---

Core/src/org/sleuthkit/autopsy/geolocation/MapPanel.java
Core/src/org/sleuthkit/autopsy/geolocation/MapWaypoint.java

Also includes file formatting updates.

Suppressed warnings for display of deprecated aritfact types

---

thirdparty/rr/plugins/arunmru.pl
thirdparty/rr/plugins/autopsylogin.pl
thirdparty/rr/plugins/autopsyntusernetwork.pl
thirdparty/rr/plugins/autopsyrecentdocs.pl
thirdparty/rr/plugins/autopsyshellfolders.pl
thirdparty/rr/plugins/officedocs.pl
thirdparty/rr/plugins/officedocs2010.pl

Check for undefined values in Autopsy regripper plugins, this is for Autopsy version of regripper not full version of regripper.

4924-Investigate-malformed-XML-produced-by-RegRipper-plugins

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java

Add "Recent File List" to check in while loop and exit if it does contain it.

6505-ArrayIndexOutOfBoundsException-in-Registry

---

Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/CentralRepository.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/PersonaAccount.java

Reverts sleuthkit/autopsy#5995

Revert "1485 - CentralRepository getInstance will throw exception when CR is disabled"

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/USB_DATA.txt

6244-Update-USB-Device_IDs

---

InternalPythonModules/android/cachelocation.py

Check number of entries of cache files to see if it is greater then the file size, if it is then skip processing of the file, otherwise process the file.

6575-Error_parsing-cached-GPS-locations-to-blackboard

---

Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/CentralRepoAccount.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/CentralRepository.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/Persona.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/PersonaAccount.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/PersonaAlias.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/PersonaMetadata.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/RdbmsCentralRepo.java
Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/SqliteCentralRepo.java
Core/test/qa-functional/src/org/sleuthkit/autopsy/centralrepository/datamodel/CentralRepoPersonasTest.java

Modified persona classes to run SQL as prepared statements.

6579: Input from user can cause SQL exceptions in Personas

---

Core/src/org/sleuthkit/autopsy/casemodule/ImageDSProcessor.java

This is not the change to make auto ingest use ingest streams, just to make it function again.

Fix auto ingest for disk images

---

build.xml
unix_setup.sh

Set the execute bit on Linux and Macos executable files.

6583-New-tools-need-execute-bit-set-for-linux-and-mac

---

Core/src/org/sleuthkit/autopsy/contentviewers/artifactviewers/Bundle.properties-MERGED
Core/src/org/sleuthkit/autopsy/contentviewers/artifactviewers/MessageAccountPanel.java

Display a message "No match found" in the Accounts tab, if no accounts can be found for a message artifact.

6581: Blank Accounts tab in message artifact viewer.

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractPrefetch.java

Added datasource to name passed to external program, make directory case check all lowercase.

6578-RecentActivity-errors-File-has-a-null-value

---

Core/src/org/sleuthkit/autopsy/ingest/Bundle.properties
Core/src/org/sleuthkit/autopsy/ingest/Bundle.properties-MERGED
Core/src/org/sleuthkit/autopsy/ingest/IngestProgressSnapshotPanel.java
Core/src/org/sleuthkit/autopsy/ingest/IngestTasksScheduler.java
Core/src/org/sleuthkit/autopsy/ingest/Snapshot.java

Fix bug where streaming queue was not emptied during cancellation.

6431 Include streaming files queue in Snapshot.

---

NEWS.txt

Fixed inaccurate note about comments.

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractPrefetch.java

Lets try this again.  Change contains to endswith to get better match.

6642-prefetch-associated-object-is-not-consistent-4-16

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractPrefetch.java

Add path to list of attributes

6675-update-prefetch-ingest-process

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/Chromium.java

Add checks for file names to ignore

6634-chromium-based-browser-bookmark-fix

---

Core/src/org/sleuthkit/autopsy/centralrepository/persona/OpenPersonasAction.java
Core/src/org/sleuthkit/autopsy/discovery/OpenDiscoveryAction.java
Core/src/org/sleuthkit/autopsy/geolocation/OpenGeolocationAction.java
Core/src/org/sleuthkit/autopsy/timeline/OpenTimelineAction.java
Experimental/src/org/sleuthkit/autopsy/experimental/autoingest/AutoIngestDashboardOpenAction.java

Changed the position of other Actions to remove warnings about duplication.

6758 Moved the Personas menu option farther down in the Tools list.

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/SEUQAMappings.xml

Update Mappings, validate and verify xml file.

6617-Research-search-URLS-to-enable-update

---

Core/src/org/sleuthkit/autopsy/contentviewers/artifactviewers/CallLogArtifactViewer.java
Core/src/org/sleuthkit/autopsy/contentviewers/artifactviewers/MessageAccountPanel.java

Fix bug related to call logs with no direction.

6761 Don't display device ID under accounts.

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/SEUQAMappings.xml
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/SearchEngineURLQueryAnalyzer.java

General changes to use existing APIs.
Depends on https://github.com/sleuthkit/sleuthkit/pull/2016

6694 Test multiple matching search engines.

---

Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java

Check to see if dataSource if LocalFilesDataSouce, if not then exit gracefully

6846-ILeapp-Analyser-needs-to-check-dataSource-type-to-see-if-it-can-run

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java

Look for " [" instead of "[" in sam group name.

6836-NumberFormatException-Reading-Group-Information-in-Regripper-Sam-Output

---

Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappFileProcessor.java

Remove stack trace and add attribute name and file name where the date parse error is occuring.

6853-Enhance-iLeapp-Parse-Warning-Messages

---

Core/src/org/sleuthkit/autopsy/discovery/search/DiscoveryEventUtils.java
Core/src/org/sleuthkit/autopsy/discovery/search/DomainSearchArtifactsLoader.java
Core/src/org/sleuthkit/autopsy/discovery/search/DomainSearchCacheLoader.java
Core/src/org/sleuthkit/autopsy/discovery/search/DomainSearchThumbnailLoader.java
Core/src/org/sleuthkit/autopsy/discovery/ui/DiscoveryTopComponent.java
Core/src/org/sleuthkit/autopsy/discovery/ui/ResultsPanel.java

This PR builds off of https://github.com/sleuthkit/autopsy/pull/6328. The last commit include the relevant changes to review.

6886 - Discovery UI Background Task Cancellation

---

Core/test/unit/src/org/sleuthkit/autopsy/discovery/search/DomainSearchCacheLoaderTest.java

Greg pointed out to me that I forgot to update my own tests in a recent PR.

Fixed broken domain search tests

---

Core/src/org/sleuthkit/autopsy/modules/ileappanalyzer/ILeappAnalyzerIngestModule.java

ios-analyser-error-14.17.0-release

---

Core/src/org/sleuthkit/autopsy/modules/embeddedfileextractor/PDFAttachmentExtractor.java

Reverts sleuthkit/autopsy#6378

Revert "Extract inline images from PDF"

---

KeywordSearch/solr/server/solr/configsets/AutopsyConfig/conf/schema.xml
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/Server.java

* Updated deprecated schema fields. 
* Improved check for existing collections

Updated deprecated Solr8 schema fields (6990)

---

thirdparty/rr-full/plugins/shellactivities.pl

7008-Regripper-Plugin-Shellactivities-has-an-infinite-loop

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractSru.java

Cleaned up path displayed and make sure file is resolved.

7043-clean-SRUM-path-before-resolving

---

thunderbirdparser/nbproject/project.properties
thunderbirdparser/nbproject/project.xml
thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/MboxParser.java

Added email validator and code for checking if a file is mbox format or not

7005-Email-parser-error

---

thirdparty/rr-full/shellitems.pl

Fix infinite loop that occurs because it could not find specific data.

7085-regripper-shellbags-hanging

---

thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/MboxParser.java
thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/ThunderbirdMboxFileIngestModule.java

If the first few bytes of a file contain "From" then check mimetype, if the mimeType is null or empty then use tika to determine mimetype of the file.

7116-Email-parser-ingest-module-failing-to-parse-mbox-file

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java

Add data to ignore in trust records from regripper output.

7147-ArrayINdexOutOfBoundsException-in-Registry

---

test/script/tskdbdiff.py

...to have a place holder instead of artifactID

7201 - Changed the tsk_event_decription other descriptions 

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java

Add locale of US to SimpleDateFormat.  This is same things as PR 5827 and replaces that PR.

7200-Fix-date-parsing-errors-when-system-locale-is-not-Locale.US-replaces-PR-5827

---

Core/src/org/sleuthkit/autopsy/modules/leappanalyzers/LeappFileProcessor.java
Core/src/org/sleuthkit/autopsy/modules/leappanalyzers/aleap-artifact-attribute-reference.xml

Fix xml file and code for data.  Added newer version of aLeapp

7213-fixes-in-xml-for-aleapp

---

Core/src/org/sleuthkit/autopsy/modules/leappanalyzers/aleap-artifact-attribute-reference.xml
Core/src/org/sleuthkit/autopsy/modules/leappanalyzers/ileap-artifact-attribute-reference.xml

7214 fixes in ileapp

---

nbproject/project.properties

Reverts sleuthkit/autopsy#6671

Revert "Temporarily flip build back to development"

---

docs/doxygen-user/multi-user/installSolr.dox

fix-typo-in-solr-install-doc

---

Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/CorrelationAttributeNormalizer.java
Core/src/org/sleuthkit/autopsy/modules/leappanalyzers/LeappFileProcessor.java

Normalize Domain name to TSK/CR standards

7242-aLEAPP/iLEAPP-parsing/sanitization-of-tsv-data-to-match-TSK-expectations

---

Core/src/org/sleuthkit/autopsy/datamodel/HostNode.java

4138: HostManager returns a list instead of a set.

---

Core/src/org/sleuthkit/autopsy/casemodule/AddImageTask.java
Core/src/org/sleuthkit/autopsy/casemodule/ImageDSProcessor.java
Core/src/org/sleuthkit/autopsy/casemodule/LocalDiskDSProcessor.java
Core/src/org/sleuthkit/autopsy/logicalimager/dsp/AddMultipleImagesTask.java

Depends on https://github.com/sleuthkit/sleuthkit/pull/2184

Remove host parameter

---

Core/src/org/sleuthkit/autopsy/datamodel/HostNode.java
Core/src/org/sleuthkit/autopsy/datamodel/hosts/Bundle.properties-MERGED
Core/src/org/sleuthkit/autopsy/datamodel/hosts/MergeHostAction.java
Core/src/org/sleuthkit/autopsy/datamodel/hosts/MergeHostMenuAction.java
Core/src/org/sleuthkit/autopsy/directorytree/Bundle.properties-MERGED
Core/src/org/sleuthkit/autopsy/directorytree/ExportCSVAction.java

Fixed capitalization on csv menu option.
Depends on https://github.com/sleuthkit/sleuthkit/pull/2232

7326 Add context menu to merge hosts.

---

nbproject/platform.properties

Signed-off-by: Luís Ferreira <contact@lsferreira.net>
---
Fixes #6773

Fix #6773 - CI and packaging is failing due to outdated netbeans link

---

Core/src/org/sleuthkit/autopsy/casemodule/Case.java
Core/src/org/sleuthkit/autopsy/casemodule/events/OsAccountRemovedEvent.java
Core/src/org/sleuthkit/autopsy/datamodel/OsAccounts.java

Depends on https://github.com/sleuthkit/sleuthkit/pull/2247

7349 Handle OS account removed event

---

Core/src/org/sleuthkit/autopsy/contentviewers/osaccount/OsAccountDataPanel.java
Core/src/org/sleuthkit/autopsy/datamodel/OsAccounts.java

https://github.com/sleuthkit/sleuthkit/pull/2263

Temporary change to not load the realm

---

Core/src/org/sleuthkit/autopsy/datamodel/HostNode.java
Core/src/org/sleuthkit/autopsy/datamodel/hosts/AssociateNewPersonAction.java
Core/src/org/sleuthkit/autopsy/datamodel/hosts/AssociatePersonAction.java
Core/src/org/sleuthkit/autopsy/datamodel/hosts/RemoveParentPersonAction.java

Depends on https://github.com/sleuthkit/sleuthkit/pull/2285

7478 Updates for person/host refactor

---

Experimental/src/org/sleuthkit/autopsy/experimental/autoingest/AutoIngestManager.java

Allow cancellation in SHUTTTING_DOWN state.

7458 Set the data source processor so it can be cancelled if needed.

---

Core/src/org/sleuthkit/autopsy/modules/leappanalyzers/LeappFileProcessor.java
Core/src/org/sleuthkit/autopsy/modules/leappanalyzers/ileap-artifact-attribute-reference.xml

Get current iLeapp executable with fixes.
make iLeapp xml map correctly.

7255-upgade-ileapp-aleapp-executables

---

Core/src/org/sleuthkit/autopsy/modules/leappanalyzers/LeappFileProcessor.java

7507-fix-LeappFileProcessor.createMessageRelationship

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java

Add check for zero length file and ignore it if it is.

7526-Check-system-registry-hive-is-not-zero-bytes-in-length

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractPrefetch.java

Check if thirdparty database file exists before trying to process it.

7524-check-to-see-if-prefetch-thirdparty-database-exists

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ParseRegistryHive.java

Handle key not found exception
Fix check for realm scope when creating user.

7525-Searching-For-registry-key-returns-error-if-no-found

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java

Add domain to beginning of the file name to make it unique to avoid other processes not being able to write to the file.

7528-Error-in-Processing-Registry-File-possibly-still-open-in-another-process

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/Server.java

No longer attempting to index new data after 5 failed consecutive attempts

Solr indexing retries (7521)

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ChromeCacheExtractor.java

Check for buffer capacity of zero (0) and return if it is, nothing to look at.

7537-IllegalArgumentException-in-Chromium-RA-module

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractPrefetch.java

Change error logging to warning
Add file name that warning is occurring on
Add detail message to warning

7450-Missing-database-table-error-during-prefetch-file-parsing

---

thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/VcardParser.java

Check if telephone uri is null and return if it is.

7541-NPE-in-Email-parser

---

Core/src/org/sleuthkit/autopsy/modules/vmextractor/VMExtractorIngestModule.java

Check if valid VHD files are in the list of files to extract.

7631-Use-Signatures-for-VHD-detection-in-VM-extractor-ingest-module

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java

Check length of Tokens after split, if they are not greater than 2 then skip trying to parse the token.

7649-ArrayIndexOutOfBoundsException-in-Recent-Activity

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java
thirdparty/rr-full/plugins/samparse.pl

Change code to support encoded characters from regripper and reading them from regripper output file.

7650-Failed-to-create-OsAccount-error

---

Core/src/org/sleuthkit/autopsy/datamodel/ImageNode.java

This is only the changes for the ImageNode part of this story.

7646 - Removed db calls from ImageNode createSheet

---

Core/src/org/sleuthkit/autopsy/report/modules/portablecase/PortableCaseReportModule.java

Depends on https://github.com/sleuthkit/sleuthkit/pull/2451

7698 Copy DataArtifacts and AnalysisResults into the portable case

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/RAImageIngestModule.java

move run of recycle bin to beginning of the recent activity run

7695-Move-Recyclebin-Extractor-in-Recent-Activity-to-Run-Before-Recent-Documents

---

Core/src/org/sleuthkit/autopsy/corecomponents/DataArtifactContentViewer.java

:7832-Clean-up-DataArtifactContentViewer.isPreferred()-to-remove-the-concept-of-ANALYSIS_RESULT

---

Core/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/CaseEventListener.java
Core/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/IngestEventsListener.java
Core/src/org/sleuthkit/autopsy/centralrepository/ingestmodule/CentralRepoIngestModule.java

Depends on https://github.com/sleuthkit/sleuthkit/pull/2504

7867 Move past cases to TSK_OTHER_CASES

---

Core/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/IngestEventsListener.java

Depends on https://github.com/sleuthkit/sleuthkit/pull/2506

7848 Temporary code to flag matching personas

---

Core/src/org/sleuthkit/autopsy/ingest/IngestTaskPipeline.java

7896 Fix deadlock introduced by synchronization of IngestTaskPipeline methods

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractJumpLists.java

Fix path where temp files and derived files are written for Multiuser case

7884-Thousands-of-FileNotFoundException-exceptions

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ShellBagParser.java
thirdparty/rr-full/plugins/shellbags.pl
thirdparty/rr-full/plugins/shellbags_test.pl
thirdparty/rr-full/plugins/shellbags_xp.pl
thirdparty/rr-full/shellitems.pl

Parse Unicode characters in shellbags

7892-Review-ShellBags-code-for-corrupt-characters

---

thirdparty/rr-full/plugins/shellbags_xp.pl

Fix output of characters for shellbags_xp

7892-fix-rr-shellbag-xp

---

Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/CorrelationAttributeUtil.java
Core/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/IngestEventsListener.java
Core/src/org/sleuthkit/autopsy/datamodel/BlackboardArtifactNode.java
Core/src/org/sleuthkit/autopsy/datamodel/DisplayableItemNode.java
Core/src/org/sleuthkit/autopsy/datasourcesummary/datamodel/TypesSummary.java
Core/src/org/sleuthkit/autopsy/discovery/search/DomainSearch.java
docs/doxygen-user/main.dox

Fix doxygen warnings.

---

Core/src/org/sleuthkit/autopsy/datamodel/BlackboardArtifactItem.java
Core/src/org/sleuthkit/autopsy/datamodel/BlackboardArtifactNode.java

This reverts commit e2b92669f5aa03a901f2e245a6be3f6a498a3ad5.

Revert "7989 temp fix for 'sliced' artifact objects"

---

RecentActivity/src/org/sleuthkit/autopsy/recentactivity/Bundle.properties-MERGED
RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ChromeCacheExtractor.java

Fix illegalArgument Exception with corrupt cache files.

8005-IllegalArgumentException-in-Chromium-RA-module

---

Core/src/org/sleuthkit/autopsy/discovery/search/SummaryHelpers.java

Make returned message more meaning full

:7934-no-preview-available-for-PPT-in-file-discovery-tool

---

Core/src/org/sleuthkit/autopsy/discovery/search/SummaryHelpers.java

7934-no-preview-available-for-PPT-in-file-discovery-tool

---

Core/src/org/sleuthkit/autopsy/centralrepository/contentviewer/OtherOccurrencesPanel.java
Core/src/org/sleuthkit/autopsy/contentviewers/MediaViewImagePanel.java
Core/src/org/sleuthkit/autopsy/guiutils/JFileChooserFactory.java

Set thread name in classes that were missing it.

8052 Add name of calling class to the JFileChooser background thread.

---

Core/src/org/sleuthkit/autopsy/mainui/datamodel/AnalysisResultDAO.java
Core/src/org/sleuthkit/autopsy/mainui/datamodel/AnalysisResultSearchParam.java
Core/src/org/sleuthkit/autopsy/mainui/datamodel/BlackboardArtifactDAO.java
Core/src/org/sleuthkit/autopsy/mainui/datamodel/BlackboardArtifactSearchParam.java
Core/src/org/sleuthkit/autopsy/mainui/datamodel/DataArtifactDAO.java
Core/src/org/sleuthkit/autopsy/mainui/datamodel/DataArtifactSearchParam.java
Core/test/qa-functional/src/org/sleuthkit/autopsy/mainui/datamodel/TableSearchTest.java

Depends on https://github.com/sleuthkit/sleuthkit/pull/2595

8098 Optimize artifact loading

---

Core/src/org/sleuthkit/autopsy/datasourceprocessors/xry/XRYCallsFileParser.java
Core/src/org/sleuthkit/autopsy/datasourceprocessors/xry/XRYMessagesFileParser.java
KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/RegexQuery.java
thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/ThunderbirdMboxFileIngestModule.java
thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/VcardParser.java

Update createAccountFileInstance() calls.

8258 Add attributes to credit card hit artifact.

---

Core/src/org/sleuthkit/autopsy/mainui/datamodel/FileSystemDAO.java
Core/src/org/sleuthkit/autopsy/mainui/nodes/FileSystemFactory.java

8225 Invalidate file system tree for unalloc space images.

---

pythonExamples/dataSourceIngestModule.py
pythonExamples/fileIngestModule.py

Update Examples to work with the latest version of Autopsy.

Update Examples to Work With Latest Version of Autopsy

---

Core/src/org/sleuthkit/autopsy/centralrepository/CentralRepoSettings.java
Core/test/qa-functional/src/org/sleuthkit/autopsy/centralrepository/datamodel/CentralRepoDatamodelTest.java

hardcoding property file location to avoid qa functional classloader issues

central repo test fix

---

NEWS.txt

Update new with new version number
add new ingest module

Update news with version and new ingest module

---

KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/LuceneQuery.java

Reverts sleuthkit/autopsy#7771

Revert "Revert "Lowercase the search term for UI""

---

thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/PstParser.java
thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/ThunderbirdMboxFileIngestModule.java

Add column to show email has an attachment.  Referenced in Issue https://github.com/sleuthkit/autopsy/issues/7358

Add has attachment to email

---

Core/src/org/sleuthkit/autopsy/contentviewers/artifactviewers/DefaultTableArtifactContentViewer.java

Current default artifact viewer would only show JSON whose root item was a JSON object.  This provides a fix where the root object is a primitive or JSON array.

fix for json array attribute value

---

docs/doxygen-dev/Doxyfile
docs/doxygen-user/Doxyfile
docs/doxygen-user_fr/Doxyfile
docs/doxygen/Doxyfile

Update the version numbers for doxy help

Update version numbers for Doxy help
