- Core/build.xml
- Core/manifest.mf
- Core/nbproject/project.xml
- Core/src/org/sleuthkit/autopsy/corecomponents/Bundle.properties
- Core/src/org/sleuthkit/autopsy/corecomponents/OnlineHelpAction.java
- KeywordSearch/nbproject/project.xml
1. *Help Content* under *Help* menu removed.
2. It is replaced by *Online Documentation* which links to [Autopsy User Documentation](http://sleuthkit.org/autopsy/docs/user-docs/3.1/)
3. This Online Documentation opens in the system browser by default. If not supported, it opens in the built-in browser.
> Doxygen user docs

- build-windows.xml
- build.xml
To build Autopsy, you must have a 64-bit version of PostgreSQL installed. It is available at http://www.postgresql.org/download/
You need to define an environment variable called POSTGRESQL_HOME_64 and point it to the PostgreSQL folder containing but not including the bin folder.
Here is an example: 
POSTGRESQL_HOME_64=C:\Program Files\PostgreSQL\9.4
In Visual Studio, build The SleuthKit (TSK) selecting one of following targets:
Debug_PostgreSQL x64
Release_PostgreSQL x64
Then, in NetBeans, build the DataModel with "Clean and Build"
Then, also in NetBeans, build Autopsy with "Clean and Build"
For those interested in just using TSK and the DataModel:
Build TSK with non-PostgreSQL targets in Visual Studio.
Then, build the DataModel with two steps:
1) clean 
2) select one of the two …
> Default build target now builds for PostgreSQL + SQLite

- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/KeywordSearchResultFactory.java
- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/LuceneQuery.java
- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/QueryResults.java
> KeywordSearchResultFactory.getOneHitPerObject() returns consistent results

- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/TagUtils.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ThumbnailCache.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/Category.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableDB.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableFile.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/grouping/GroupManager.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/GroupPane.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/SingleDrawableViewBase.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/SummaryTablePane.java
Better cleanup of the groupPane.
Print fewer exceptions that come from the case closing.
Re-use the same worker thread.
> Fixes for Image Gallery case changing/closing

- Core/src/org/sleuthkit/autopsy/ingest/IngestManager.java
- Core/src/org/sleuthkit/autopsy/report/ReportGenerator.java
Note that when keyword hits returns different snippets (keyword hits) for the same file, the sort order is negatively affected. This should be resolved by fixing the which-snippet-is-first issue.
Remove debug code
> fix report sort order between Postgres and SQLite

- Core/src/org/sleuthkit/autopsy/directorytree/DirectoryTreeTopComponent.java
The propertyChange() override in DirectoryTreeTopComponent can now be called in a JMS thread running the code starting in RemoteEventPublisher.onMessage(). This change dispatches UI changes to the EDT.
> Make sure property change handlers dispatch to EDT

- Core/src/org/sleuthkit/autopsy/directorytree/DirectoryTreeTopComponent.java
- Core/src/org/sleuthkit/autopsy/filesearch/DateSearchFilter.java
- Core/src/org/sleuthkit/autopsy/timeline/TimeLineController.java
- Makes TimelineController and DataSearchFilter do UI updates in EDT now that their propertyChange() implementations can be called from a JMS thread.
- Updates IDE formatting for TimelineController.
- Removes dead code and fixes some weaknesses flagged by the IDE in DirectoryTreeTopComponent and TimelineController.
> Ensure code executed on JMS thread dispatches to EDT

- Core/src/org/sleuthkit/autopsy/directorytree/DirectoryTreeTopComponent.java
- Core/src/org/sleuthkit/autopsy/filesearch/DateSearchFilter.java
- Core/src/org/sleuthkit/autopsy/timeline/TimeLineController.java
- Fix warning for fall through in DateSearchFilter class
- Convert anonymous inner classes to member reference invocations and lambdas in DirectoryTreeTopComponent, TimelineController, and DateSearchFilter.
> Fix warning in DateSearchFilter, do some member ref/lamda conversions

- Core/src/org/sleuthkit/autopsy/casemodule/Case.java
- Core/src/org/sleuthkit/autopsy/casemodule/events/ReportAddedEvent.java
- Adds a "lazy-loading" ReportAddedEvent class, avoiding making the TSK DataModel Report class Serializable for now, at least.
> Correct implementation of Case.REPORT_ADDED event

- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/TagUtils.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/AddDrawableTagAction.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/AddTagAction.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/CategorizeAction.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/Category.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableDB.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableFile.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/grouping/GroupManager.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/GroupPane.java
- Keep some file data in memory to avoid excessive database queries (list of image file IDs, image/video, and category counts)
- When categorizing/tagging a group, don't create tiles (including thumbnails) for images that aren't on the screen
- Changed locking around Category and Tag listeners to prevent slowdown/deadlocks
> Various Image Gallery performance improvements.

- Core/src/org/sleuthkit/autopsy/modules/photoreccarver/PhotoRecCarverFileIngestModule.java
context = null when context.processingUnallocatedSpace() is set false and Photorec Carver module is run.
> NPE in case of removed photorec carver job handled

- Core/src/org/sleuthkit/autopsy/examples/SampleFileIngestModule.java
obvious error that prevents process() from running in the normal case;
could be confusing to newcomers (which is who examples are really aimed toward)
> fix small error (inverted logic)

- Core/src/org/sleuthkit/autopsy/modules/embeddedfileextractor/EmbeddedFileExtractorIngestModule.java
Embedded File Extractor Module no longer logs "Procession XYZ file..." messages.
> Excession logging issue fixed

- Core/src/org/sleuthkit/autopsy/casemodule/Case.java
- Core/src/org/sleuthkit/autopsy/casemodule/CollaborationMonitor.java
Fixes a bug and cleans up IDE's brain-dead "refactoring" of comments.
> Shut down remote task progress bars when case is closed

- Core/src/org/sleuthkit/autopsy/modules/exif/ExifParserFileIngestModule.java
fileTypeDetector.getFileType(f) may return null and cause NPE to be thrown.
> null check for value returned by getFileType(AbstractFile)

- Core/src/org/sleuthkit/autopsy/python/JythonModuleLoader.java
Replace last occurrence of ".py" in a file name instead of any occurrence of ".py" in the file name.
> jython moduleName getting regex fixed

- pythonExamples/reportmodule.py
rather than hardcoding backslash
> Use os.path.join() for path manipulation in reportmodule.py,

- thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/MboxParser.java
NPE thrown in case of invalid message format.
> NPE and other runtime exceptions possibly thrown handled

- Core/src/org/sleuthkit/autopsy/datamodel/FileTypeExtensions.java
- Core/src/org/sleuthkit/autopsy/modules/embeddedfileextractor/Bundle.properties
- Core/src/org/sleuthkit/autopsy/modules/embeddedfileextractor/SevenZipExtractor.java
1. sevenzipjbinding supports application/x-gtar mimetype
3. If archive content size is unknown, extraction is still performed; free disk space is examined as while writing data to disk. If the content to be written is more than 80% of the free disk space, write operation is aborted.
3. The partially extracted file is deleted.
NOTE: Extraction IS performed if the ingest monitor cannot ascertain the free disk space (IngestMonitor.DISK_FREE_SPACE_UNKNOWN).
> extract content from archive having unknown size - sevenzipextractor

- Core/src/org/sleuthkit/autopsy/events/RemoteEventPublisher.java
* Applications not running interactively also need to receive remote events. We need to figure out how to handle case closing issue differently.
* Removed a check to make sure that there is a currently open case. Remote events may not be related to current case. It can be a status/priority/UI update.
> Remote publisher changes

- Core/src/org/sleuthkit/autopsy/report/ReportHTML.java
makes row for unallocated/unused blocks in the HTML report
does not save unallocated/unused blocks to disk.
> tagged unallocated space reported

- Core/src/org/sleuthkit/autopsy/ingest/IngestJobSettings.java
1. changes to jython-standalone-2.7.0.jar ensure that serialVersionUID remains same after reloading jython module.
2. serialVersionUID is added as a part of module settings file name in order to handle situation where two python modules have same factory class names.
> Python ingest settings

- Core/src/org/sleuthkit/autopsy/ingest/IngestJobSettings.java
- Core/src/org/sleuthkit/autopsy/python/Bundle.properties
- Core/src/org/sleuthkit/autopsy/python/JythonModuleLoader.java
- docs/doxygen/modDevPython.dox
1. Reload py module only if python module content is modified (eg new files added/ existing file content modified) since the last usage (IngestModuleFactoryLoader.getIngestModuleFactories()).
2. Maintain a list of modules and their last usage timing; serialized to the disk.
NOTE: Deletion of files from the module folder will not cause reload.
> Python settings persistence

- Core/src/org/sleuthkit/autopsy/casemodule/Case.java
- Core/src/org/sleuthkit/autopsy/casemodule/IntervalErrorReportData.java
- Modified Case class to be TSK error subscriber again
- Modified Case class to use non-static SleuthkitCase ErrorObserver API 
- Made IntervalErrorReportObserver no longer be a singleton
- Modified Case class create and destroy instances of IntervalErrorReportObserver in changeCase(), analogous to the way new CollaborationMonitors are made for each case
> Error observer api devel

- Core/src/org/sleuthkit/autopsy/casemodule/Case.java
- Core/src/org/sleuthkit/autopsy/ingest/DataSourceIngestJob.java
- Core/src/org/sleuthkit/autopsy/ingest/IngestJob.java
- Core/src/org/sleuthkit/autopsy/ingest/IngestManager.java
- Core/src/org/sleuthkit/autopsy/ingest/IngestMonitor.java
- Add cancellation reasons to ingest jobs and their constituent data source ingest jobs (and to snapshots)
- Fix bug in IngestJob.start
- Make DataSourceIngestJob cancellation reflect whether or not job was completed, i.e., no cancellation for individual job if it was not still running
- Formatting
> Add ingest cancellation reasons

- Core/src/org/sleuthkit/autopsy/casemodule/AddImageAction.java
- Core/src/org/sleuthkit/autopsy/casemodule/AddImageWizardAddingProgressPanel.java
- Core/src/org/sleuthkit/autopsy/casemodule/AddImageWizardChooseDataSourcePanel.java
- Core/src/org/sleuthkit/autopsy/casemodule/AddImageWizardIngestConfigPanel.java
- Core/src/org/sleuthkit/autopsy/casemodule/AddImageWizardIterator.java
- Core/src/org/sleuthkit/autopsy/casemodule/Bundle.properties
- Core/src/org/sleuthkit/autopsy/casemodule/Bundle_ja.properties
A flag variable was being accesses by two different threads without any sort of synchronization. That has been fixed, along with dead code removal and extensive commenting, including a comment referencing a new story in JIRA about how the storeSettings method of the ingest module config panel is always called twice.
> Fix thread safety, clean up add data source wizard classes

- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java
Fixed bundle tags. Removed one empty string tag. Fixed duplicate tag issue. 
This fix by itself will not auto-merge because you reverted all of the changes from "redo 1" that this code depends on. However, if you can re-apply the changes from "redo 1" and then apply these changes on top of that, it should all be ready to go.
> 1501 ja image gallery - redo 2

- Core/src/org/sleuthkit/autopsy/corecomponents/ThumbnailViewNode.java
- Core/src/org/sleuthkit/autopsy/coreutils/VideoUtils.java
- handle exceptions better in  VideoUtils.generateVideoThumbnail()
- update copyright dates
- put cleanup code in finally block
> make sure to kill the progressHandle and timer even if exception is thrown, eg, when case is closed

- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ThumbnailCache.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/AddDrawableTagAction.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/CategorizeAction.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/DeleteFollowUpTagAction.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/OpenExternalViewerAction.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/CategoryManager.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableAttribute.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableDB.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableFile.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableTagsManager.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/ImageFile.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/VideoFile.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/grouping/GroupManager.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/VideoPlayer.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/DrawableTile.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/DrawableTileBase.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/DrawableUIBase.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/DrawableView.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/GroupPane.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/MetaDataPane.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/gui/drawableviews/SlideShowView.java
- remove type paramater from DrawableFile since it was not adding anything usefull and cluttered up the code
- add getters  that delegate to private AbastractFile instance
- refactor methods on DrawableTagsManager to deal with Content or DrawableFile objects
- remove unneeded  invocation of   ImageIO.scanForPlugins() in ImageFile
> refactor DrawableFile so it no longer extends AbstractFile

- Core/src/org/sleuthkit/autopsy/report/ReportHTML.java
This will fix the display of non-ASCII chars on the summary.html page.
> Moved Content-Type meta tag from CSS style block to main head block

- Core/src/org/sleuthkit/autopsy/casemodule/CollaborationMonitor.java
- Core/src/org/sleuthkit/autopsy/core/ServicesMonitor.java
- Core/src/org/sleuthkit/autopsy/events/AutopsyEventPublisher.java
Also, added catch-all exception firewall to all tasks scheduled by a ScheduledThreadPoolExecutor
> Close remote event channel in a way that allows it to be re-opened

- Core/src/org/sleuthkit/autopsy/timeline/Bundle.properties
- Core/src/org/sleuthkit/autopsy/timeline/OpenTimelineAction.java
- Core/src/org/sleuthkit/autopsy/timeline/PerCaseTimelineProperties.java
- Core/src/org/sleuthkit/autopsy/timeline/TimeLineController.java
- Core/src/org/sleuthkit/autopsy/timeline/db/EventDB.java
- Core/src/org/sleuthkit/autopsy/timeline/db/EventsRepository.java
- Core/src/org/sleuthkit/autopsy/timeline/ui/StatusBar.java
- Core/src/org/sleuthkit/autopsy/timeline/ui/VisualizationPanel.java
no longer used deprecated SleuthKitCase.getLastObjectID() to determine if the events db is up to date.
instead respond to events by maintain a properties file with the staleness of the events db
> Tl replace last obj with .properties file based book keeping

- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractIE.java
> Treating Pasco output parsing error as warning

- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableDB.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/grouping/DrawableGroup.java
also renamed method to conform to its only existing invocation.
> use alias in sql query to avoid ambiguity about column name

- Core/src/org/sleuthkit/autopsy/datamodel/AbstractAbstractFileNode.java
* This pull request requires sleuthkit pull request 653 to be taken first
* Use new AbstractFile API to get attribute id
* Remove the unnecessary boxing of attr id as a Long with a call toString in AbstractAbstractFileNode.fillPropertyMap
> Converted attribute id from short to int

- Core/src/org/sleuthkit/autopsy/ingest/IngestManager.java
Ingest job was correctly getting cancelled by ingest manager but a valid IngestJobStartResult was being returned creating a major confusion and an ingest job that runs forever.
> 1862 Fixed a bug where ingest module startup errors were ingnored

- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/Bundle.properties
- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/HighlightedText.java
- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/KeywordSearchResultFactory.java
Actually ad-hoc substring match and regex KWS result highlighting has been broken since at least version 2.0.0.5 (November 2014). "Indexed Text" content viewer would incorrectly state that no KWS hits were found in the selected KWS result.
There were several errors in the code. There were several code paths were Solr highlighting query was getting escaped twice. In addition, all but the simplest highlighting queries were constructed and/or escaped incorrectly. The logic was also spread across several classes and different event handlers.
> 1878 Fixed a bug where indexed text content viewer erroneously reported "no keyword hits"

- BUILDING.txt
- branding/core/core.jar/org/netbeans/core/startup/Bundle.properties
- branding/modules/org-netbeans-core-windows.jar/org/netbeans/core/windows/view/ui/Bundle.properties
- build.xml
Latest java-8-oracle for Ubuntu is 1.8.0_101.
build.xml only has java-1.8.0 tests for versions with up to two-character suffixes - i.e. 1.8.0_99. Anything higher causes build to fail.
This change allows for up to three-character suffixes, i.e. 1.8.0_999.
Changes to Bundle.properties are a result of the build process and shouldn't have been included in this commit. I would remove them, but my Git kung fu isn't that strong.
> Added three-character suffix for Java in build.xml

- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/KeywordSearch.java
This error message is displayed when Solr fails to open (or close) a core.  The error message was constructing incorrect and confusing path, e.g. "Failed to open or create core for C:\case output\IN96\IN96" which sent me on a wild goose chase as to how we could possibly construct and use such a path.
> Fixed a very misleading error mesage

- Core/src/org/sleuthkit/autopsy/datamodel/FileTypesByMimeType.java
Removes possibility for null pointer error that would happen sometimes due to trying to add all of an empty container to a list. 
Also removes updates to mime type tree on content_added events, to lower number of queries during embedded file extractor.
> Clearing and filling hashmap now wrapped by same synchronized block

- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/Chunker.java
Fix an off by one error that could allow a chunk of just over the limit(32766) to be sent to Solr, since a single char might result in up to 4 utf-8 bytes being read.
> lower chunk size limit slightly to prevent reading too much

- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/TikaTextExtractor.java
check if tika returned an empty reader, and throw an exception , resulting in fallingback on the strings extractor.
> 2244 fallback on strings

- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/DropdownToolbar.java
- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/Ingester.java
- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/KeywordSearchIngestModule.java
- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/Server.java
- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/SolrSearchService.java
* Server.addDocument() checks if a core is open before using it
* Several other methods now throw NoOpenCoreException instead of either silently doing nothing or throwing a generic KeywordSearchModuleException
> Better handling of core being closed

- Core/src/org/sleuthkit/autopsy/casemodule/Case.java
For multi-user case, separates the creation of a case name from a display name from creation of a case database name. The goal is to not apply PostgreSQL-required name transformations to the case name, especially truncation.
> 2535 truncate case db name only

- Core/src/org/sleuthkit/autopsy/casemodule/Case.java
- Experimental/src/org/sleuthkit/autopsy/experimental/autoingest/AutoIngestManager.java
Removes the use of a case name lock from Case.createAsCurrentCase and restores the use of a case name lock to AutoIngestManager.openCase.
> 2547 case name lock in auto ingest

- Core/src/org/sleuthkit/autopsy/casemodule/Case.java
Uses the case directory path as the prefix for the case resources lock instead of the case name. This better insures uniqueness and groups the nodes in the Zookeeper tree, which is helpful for debugging/monitoring system behavior.
> Use case dir in case resoruces lock

- Core/src/org/sleuthkit/autopsy/casemodule/Case.java
- Core/src/org/sleuthkit/autopsy/casemodule/CaseMetadata.java
- Core/src/org/sleuthkit/autopsy/casemodule/NewCaseWizardPanel1.java
- Core/src/org/sleuthkit/autopsy/casemodule/SingleUserCaseConverter.java
- Experimental/src/org/sleuthkit/autopsy/experimental/autoingest/AutoIngestManager.java
- Experimental/src/org/sleuthkit/autopsy/experimental/autoingest/PathUtils.java
- Auto ingest is once again using the case name read from the manifest file for everything, e.g., case name coordination service locks, case directory names, etc. 
- The new case wizard is once again working strictly in terms of display name
- The Case class package access sanitizeCaseName method that briefly became a public displayNameToCaseName method is now a private  displayNameToUniqueName method. 
- Creating a case database name for PostgreSQL case databases has been moved into SleuthkitCase, just as creating the text index name was moved into the keyword search service. 
The last two changes complete the decoupling of the unique case name from resource names, laying the groundwork for us to change the way we create the unique case name from a display name without breaking the case …
> 2501 case name handling fixes

- Core/src/org/sleuthkit/autopsy/casemodule/services/TagsManager.java
- Updated copyright to 2017
- Positioned getDisplayNamesToTagNamesMap for conversion to static method
> Update copyright, rearrange TagsManager.java for modifications

- Core/src/org/sleuthkit/autopsy/casemodule/services/TagsManager.java
- Experimental/src/org/sleuthkit/autopsy/experimental/enterpriseartifactsmanager/optionspanel/ManageTagsDialog.java
- Add static getTagDisplayNames API to TagsManager
- Call new API to populate tags list component in org.sleuthkit.autopsy.experimental.enterpriseartifactsmanager.optionspanel.ManageTagsDialog.
> Add static getTagDisplayNames API to TagsManager

- Experimental/src/org/sleuthkit/autopsy/experimental/enterpriseartifactsmanager/optionspanel/ImportHashDatabaseDialog.java
now require a Organization to be selected in the ComboBox before enabling the Ok button. Also adding an Organization will re-run validation to enable the Ok button.
> Resolve issue 170 - NPE when Importing Hash Db in EAM

- Experimental/src/org/sleuthkit/autopsy/experimental/enterpriseartifactsmanager/datamodel/AbstractSqlEamDb.java
- branding/core/core.jar/org/netbeans/core/startup/Bundle.properties
- branding/modules/org-netbeans-core-windows.jar/org/netbeans/core/windows/view/ui/Bundle.properties
This plus 33e9dce resolves correlation engine issues 178 and 183 
I believe the duplicates issue was caused by old sql statements referring to device name rather than id, causing issues when ingesting images with the same name in testing. Was able to confirm that constraint violation SqlException gets thrown without this fix (due partially to running code based on our outdated fork), and is resolved with this fix. This PR resolves a few other locations where device_id should be used rather than name or was ignored.
> Convert sql statements referring to device name to use device id

- Experimental/src/org/sleuthkit/autopsy/experimental/enterpriseartifactsmanager/contentviewer/DataContentViewerOtherCases.java
- Experimental/src/org/sleuthkit/autopsy/experimental/enterpriseartifactsmanager/contentviewer/DataContentViewerOtherCasesTableModel.java
- Experimental/src/org/sleuthkit/autopsy/experimental/enterpriseartifactsmanager/datamodel/AbstractSqlEamDb.java
- use .equals() instead of == for comparison of EamArtifact.Type objects. Now imported hash db files will properly trigger hashset hits. And imported hash db files will display in the content viewer table.
- check EamArtifactInstance fields for null before displaying them in the content viewer table. global files do not have a case or data source, so need to check for null before displaying them in the content viewer table. Those nulls will be replaced with "No data.". Could go with "" if you prefer.
> Eam - properly use and display global files (hash db imported files)

- CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/AbstractSqlEamDb.java
- CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/PostgresEamDb.java
- CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/PostgresEamDbSettings.java
- CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/SqliteEamDb.java
- CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/SqliteEamDbSettings.java
Resolves CE issues 182, 203. Confirmed that proper correlation db records are created for both sqlite and postgres on ingest of the attached image for issue 203 (can @APriestman confirm please)
> On bulk inserts, disregard constraint violations due to duplicates

- CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/PostgresEamDbSettings.java
- CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/SqliteEamDbSettings.java
I added the ON CONFLICT IGNORE part back to the SQLite schema. It seems to have gotten lost during merging. Should be back to how it was.
> fixed schema errors

- Core/src/org/sleuthkit/autopsy/datamodel/KeywordHits.java
-  don't make the nodes at the same time as the keys 
- use addAll rather than adding each key to list.
> 2839 improve keyword hits tree performance

- Core/src/org/sleuthkit/autopsy/corecomponents/ThumbnailViewChildren.java
A lambda expression in an inner class had issues in dependent projects when run in the IDE, second time seeing this issue changing it to a an anon inner class eliminates the issue.
> 2763 changed lambda expression as arg to super() to anon class

- CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/PostgresEamDbSettings.java
- CentralRepository/src/org/sleuthkit/autopsy/centralrepository/datamodel/SqliteEamDbSettings.java
Fix needed after https://github.com/sleuthkit/autopsy/pull/2970
> Prevent empty strings from getting in the badTags list

- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/RegexQuery.java
* Added a "catch" for all Throwbles and re-throwing as TskCoreException
* Logging those as SEVERE and moving on to next Solr document returned by the query
> Handling potential StackOverflowError coming out of Matcher.find() (2700)

- Experimental/src/org/sleuthkit/autopsy/experimental/autoingest/AutoIngestManager.java
- Experimental/src/org/sleuthkit/autopsy/experimental/autoingest/AutoIngestSystemLogger.java
* Increased max log size to 50MB
* Removed a log entry that was deemed unnecessary
> Minor AIM system log changes (2966)

- Core/src/org/sleuthkit/autopsy/centralrepository/contentviewer/DataContentViewerOtherCasesTableCellRenderer.java
- Core/src/org/sleuthkit/autopsy/centralrepository/contentviewer/DataContentViewerOtherCasesTableModel.java
This fixes a bug that we were using the wrong column number for the known_status
> Use name of "known" column to determine color instead of index

- Experimental/src/org/sleuthkit/autopsy/experimental/autoingest/AutoIngestManager.java
Code checks for a pre-existing job, similar to how AutoIngestMonitor is currently doing it. Upon finding one, it replaces it. I'm not sure replacing it is necessary, but it's a 'safe' way to ensure we are using the absolute latest data in our completed jobs table.
> Added check for pre-existing job in completed table.

- Core/src/org/sleuthkit/autopsy/directorytree/ViewContextAction.java
Should be functionally the same, but no longer relying on 'Content' since the previous code very explicitly wants AbstractFile.
> Revised one of the ViewContextAction constructors.

- Core/src/org/sleuthkit/autopsy/ingest/DataSourceIngestJob.java
This makes it so that the EDT will not block for the job completion check; the job completion checks will occur in the ingest threads. Note that a lock that was though to be needed to keep the volatile cancelled and cancellationReason fields was removed as actually unnecessary, and getting the cancellation action completed was prioritzed over getting the cancellation message written to the ingest progress bars.  
Also, the copyright for the file was corrected.
> Remove completion check from DataSourceIngestJob.cancel

- Core/src/org/sleuthkit/autopsy/directorytree/ExtractUnallocAction.java
> When looking for unalloc files, don't stop at first VirtualDirectory found.

- Core/src/org/sleuthkit/autopsy/corecomponents/AutopsyOptionsPanel.java
Fixes to make this work as I had previously thought I had it working.
Correct Conf file is now written to User directory when modified .
Max memory a user can set can now be equal to the the system memory.
> 3330 user conf file fix

- Core/src/org/sleuthkit/autopsy/corecomponents/Installer.java
- Core/src/org/sleuthkit/autopsy/timeline/OpenTimelineAction.java
- Core/src/org/sleuthkit/autopsy/timeline/PromptDialogManager.java
lookandfeel is set to crossplatform instead of native look and feel.
>  modified look and feel to make timeline work on autopsy-linux 

- Core/src/org/sleuthkit/autopsy/casemodule/Case.java
- Core/src/org/sleuthkit/autopsy/datamodel/Reports.java
- Core/src/org/sleuthkit/autopsy/directorytree/ExternalViewerAction.java
Allow reports that are http to be opened in the default browser when right click/open or double click on the report.
> Allow http reports to be viewed when clicked

- Core/test/qa-functional/src/org/sleuthkit/autopsy/modules/encryptiondetection/EncryptionDetectionTest.java
Fixes a probable merge mistake where getOpenCase was still being used in the a test method
> Fix merge error, updating getOpenCase to getCurrentCaseThrows

- Core/src/org/sleuthkit/autopsy/filesearch/DataSourcePanel.java
Change list name to standard capitalization.
> Fix unchecked cast warning.

- Core/src/org/sleuthkit/autopsy/commonfilesearch/AllDataSourcesCommonFilesAlgorithm.java
- Core/src/org/sleuthkit/autopsy/commonfilesearch/SingleDataSource.java
No longer returns matching md5s that exist only within a single datasource.
> modify intra-case queries to filter out single datasource results

- Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/AbstractSqlEamDb.java
- Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/CorrelationDataSource.java
- Core/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/CaseEventListener.java
Don't throw an exception when attempting to add an already initialized data source
> Don't try to add new data sources to the central repo twice.

- Running_Linux_OSX.txt
Homebrew people have updated the sleuthkit installation process to our liking. Users of Autopsy in Mac OSX do not have to use --with-jni bindings during installation. Java bindings with be installed automatically.
> modified mac os X install docs

- Core/test/qa-functional/src/org/sleuthkit/autopsy/commonfilessearch/CommonAttributeSearchInterCaseTests.java
- Core/test/qa-functional/src/org/sleuthkit/autopsy/commonfilessearch/IngestedWithHashAndFileTypeInterCaseTests.java
> Modify tests to use appropriate method signature for AbstractCommonAttributeSearcher

- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/actions/NextUnseenGroup.java
minimal feed back while changing groups: disable the next unseen group button.
> 1050 IG Groups UI fixes

- Core/src/org/sleuthkit/autopsy/centralrepository/datamodel/DataSourceUpdateService.java
Addresses bug found in upgrade population of data source object id observed by @rcordovano while working on 4556
This change will add a comparison for name of datasource before assigning a data source object id so that in the situation where a data source has the same case and device id as another data source but a different data source name it will assign a correct data source object id
> 4556 fix bug in upgrade population of CR data source obj id

- unix_setup.sh
This version is a little more verbose on failures.  This should assist the end user with debugging their issue when things like the Sleuth Kit Java bindings could not be found.  Also removed the extraneous 'if' at the end since it's covered by the previous if-then check.
> Make the unix_setup.sh script a little more verbose.

- Core/src/org/sleuthkit/autopsy/textextractors/TikaTextExtractor.java
This is esp critical if we override the mimetype ourselves. We also gain a noticeable performance boost.
> Optimization and Bug fix - Make Tika use AbstractFile mimetype instead of recomputing

- Core/src/org/sleuthkit/autopsy/casemodule/Case.java
- Move call to Case.deleteCoordinationServiceNodes into CaseType.MULTI_USER_CASE block (bug fix).
- Clean up confusing null check / assert combination in Case.acquireExclusiveCaseResourcesLock and its callers. Reformat Messages annotation for Case.acquireExclusiveCaseResourcesLock.
- Format Case.createPortableCase.
> Fix case coord svc node deletion bug

- CoreLibs/ivy.xml
- We have a dependency on AppleJavaExtensions, but we are not downloading it.
> 4776: Missing jar error

- Core/src/org/sleuthkit/autopsy/textextractors/TikaTextExtractor.java
Adds an Autopsy log msg when a file fails to be parsed by Tika. Since the stack trace is being logged by the Tika logger, we simply reference this fact in Autopsy.
> 4867 Add Tika Log Statement

- Core/src/org/sleuthkit/autopsy/coreutils/StringExtract.java
When UTF-16 extraction is enabled and produces no result (on odd offsets), the null value would always win and the offset would be incremented by 1. Now, with the offset being even, UTF-16 extraction produced a non-null result... but we completely skipped a character. Changing the flag to accept only if UTF16 was actually run resolved this story.
Edit: It is worth mentioning that on this odd offset, UTF-8 contained the correct result and should have won. The change in this PR allows UTF8 the opportunity to win.
> 5071 Strings CV missing characters

- Core/src/org/sleuthkit/autopsy/contentviewers/FileViewer.java
Add validate to replace paint to show registry tree every time a registry file is selected.
> 2428 - Registry file viewer does not display content for all registry files

- Core/src/org/sleuthkit/autopsy/filequery/FileSearch.java
- Core/src/org/sleuthkit/autopsy/filequery/FileSearchPanel.java
- Core/src/org/sleuthkit/autopsy/filequery/GroupListPanel.java
- Core/src/org/sleuthkit/autopsy/filequery/SearchResults.java
Display group sizes again.
Fixed bug with parent path enabling.
> 5323 Use result object instead of hash map.

- Core/src/org/sleuthkit/autopsy/filequery/FileSearch.java
- Core/src/org/sleuthkit/autopsy/filequery/FileSearchData.java
Mark files with no matches as UNIQUE.
Fix the CR enums.
Count cases for frequency instead of data sources
> 5352 CR frequency fixes/only count cases

- Core/test/qa-functional/src/org/sleuthkit/autopsy/commonpropertiessearch/CommonAttributeSearchInterCaseTest.java
- Core/test/qa-functional/src/org/sleuthkit/autopsy/commonpropertiessearch/IngestedWithHashAndFileTypeInterCaseTest.java
- Core/test/qa-functional/src/org/sleuthkit/autopsy/commonpropertiessearch/IngestedWithHashAndFileTypeIntraCaseTest.java
- Core/test/qa-functional/src/org/sleuthkit/autopsy/commonpropertiessearch/IngestedWithNoFileTypesIntraCaseTest.java
- Core/test/qa-functional/src/org/sleuthkit/autopsy/commonpropertiessearch/MatchesInAtLeastTwoSourcesIntraCaseTest.java
- Core/test/qa-functional/src/org/sleuthkit/autopsy/commonpropertiessearch/UningestedCasesIntraCaseTest.java
Take for example the ingest package tests. Netbeans will literally run something like: "ant -f Core -Dtest.includes=org/sleuthkit/autopsy/ingest/**/*Test.java test-single" to gather and execute the ingest tests. This is fine because all ingest test files end with 'Test.java'. The test files in commonpropertiessearch package, however, all end with 'Tests.java' so Netbeans is missing them. This means you cannot test them from Netbeans and they are not being run in the nightly builds. 
This PR changes the name so that they are rediscovered.
> Rename test files to end with "Test"

- test/script/tskdbdiff.py
This PR fixes the CSV split for "INSERT INTO .... VALUES (a, b, c, d,)" statements. Our current approach is fooled if a or b is a string containing a comma.
This will fix regression failures on the tsk_event_descriptions table. However, this may introduce corrected diffs as this split routine was used by all INSERT statements.
> Fix TskDbDiff CSV Splitting

- Experimental/src/org/sleuthkit/autopsy/experimental/textclassifier/TextClassifierTrainerReportModule.java
It looks like misunderstood the problem, but now I have the solution. The error happens during training, not model writing. 
While training, the TwoPassDataIndexer writes all the processed training data to a temporary file for later processing. This temporary file is what has the size limit. There's not way to change what a TwoPassDataIndexer does to get around this limit. The solution is to use a OnePassDataIndexer instead.
> 5452 Avoid the "java.io.UTFDataFormatException: encoded string too long" error

- test/script/tskdbdiff.py
The artifact ids were not being substituted for their types in the tsk event descriptions table for multi_user but were for single_user. I found this bug in the script. The first string (table in quotes) looks like the sqlite insert syntax, the second is for postgres. Seems like a copy and paste error if you take into account the previous line.
> Fixed typo for postgres table names

- InternalPythonModules/android/general.py
- filter out Null & blank strings while appending attachments list to msg body.
> 5587: Error from ShareIt module

- thirdparty/rr-full/plugins/itempos.pl
Fix getting long file name string. If the extension verison was not a x03, x07 or x08 the start position was set to null to get the string so it would start at the beginning of the block so would get junk data.  This change has also been pushed to the Regripper2.8 repo as well
> 5629-shellbag-data-from-regripper-is-incorrect

- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/BulkDrawableFilesTask.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/ImageGalleryController.java
- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableDB.java
For DrawableDB.insertOrUpdateDataSource, a single INSERT OR REPLACE SQL command for the image gallery datasources table is no longer viable as a dual purpose insert/update operation now that deleting rows in that table cascades to other tables. This PR implements branching to use either INSERT or UPDATE SQL, depending on whether a given data source has already been added to the image gallery database.
Note that I also made the DrawableDB.insertOrUpdateDataSource method propagate exceptions to its callers, consistent with our error handling policy.
> Rework INSERT OR REPLACE in DrawableDB for cascading data source deletes

- Core/src/org/sleuthkit/autopsy/communications/relationships/RelationshipBrowser.java
Set selected index for panel back to summary for each selection instead of staying on the currently selected tab
> 5801-cvt-should-change-to-summary-panel-when-account-selection-changes

- Core/src/org/sleuthkit/autopsy/timeline/EventsModel.java
- Core/src/org/sleuthkit/autopsy/timeline/TimeLineController.java
- Core/src/org/sleuthkit/autopsy/timeline/actions/ResetFilters.java
- Core/src/org/sleuthkit/autopsy/timeline/ui/filtering/Bundle.properties-MERGED
- Core/src/org/sleuthkit/autopsy/timeline/ui/filtering/FilterSetPanel.java
- Core/src/org/sleuthkit/autopsy/timeline/ui/filtering/datamodel/CompoundFilterState.java
- Core/src/org/sleuthkit/autopsy/timeline/ui/filtering/datamodel/SqlFilterState.java
- Core/src/org/sleuthkit/autopsy/timeline/utils/FilterUtils.java
* Made all timeline filters disabled by default. This way the lack of file types if ingest has not been run does not produce an empty display by default.
* Changed filter display names as desired by Brian Carrier.
* Changed reset button label from "Default" to "Reset" as desired by Brian Carrier. 
See also: https://github.com/sleuthkit/sleuthkit/pull/1704.
> 5804 No timeline data if some ingest modules not run

- Core/nbproject/project.xml
- Core/src/org/sleuthkit/autopsy/datamodel/ExtractedContent.java
- Core/src/org/sleuthkit/autopsy/directorytree/DataResultFilterNode.java
- Core/src/org/sleuthkit/autopsy/directorytree/DirectoryTreeFilterNode.java
- Core/src/org/sleuthkit/autopsy/directorytree/DirectoryTreeUtils.java
- Core/src/org/sleuthkit/autopsy/directorytree/FilterNodeUtils.java
- thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/Bundle.properties-MERGED
- thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/ThunderbirdMboxFileIngestModule.java
- Use CommunicationsArtifactsHelper to add the attachments to email messages.
- Updated the DirectoryTree & DataResultsTable to not show message artifacts for 'new' cases, but continue to show them for older cases.
> 5709: Email attachments

- ImageGallery/src/org/sleuthkit/autopsy/imagegallery/datamodel/DrawableDB.java
Delete data source from image_gallery_groups table when data source is deleted from image gallery
> 5902-image_gallery_groups-table-still-has-entries-for-deleted-datasources

- Core/src/org/sleuthkit/autopsy/datamodel/BlackboardArtifactNode.java
Get file name instead of artifact name for when you hover over the artifact
> 5918-Hover-text-for-Source-File-column-for-artifacts-is-incorrect

- Core/src/org/sleuthkit/autopsy/coreutils/ModuleSettings.java
- Improved documentation (IMO).
- Adding a static Logger, per convention.
- Removed noisy INFO logging.
- Added some detail to actual error messages and boosted them from WARNINGs to SEVEREs since inability to read/write settings files will affect the results of analysis of cases.
- Fixed of IDE “lightbulb” issues, e.g., using try-with-resources.
- Removed duplication of setting file path construction.
- Shifted the private constructor to the bottom of the file (I admit this was a matter of taste alone).
- Made use of synchronization consistent.
> 931 Clean up ModuleSettings.java and improve logging

- Running_Linux_OSX.txt
The latest version of Bellsoft Java 1.8.0_242 is not packaging JavaFX however the older version still is. Recommend updating the documentation to instruct users to install the slightly older version of Bellsoft Java until this is rectified. My editor also stripped trailing white space hence those changes in the diff.
> The latest version of Bellsoft Java 1.8.0_242 is not packaging JavaFX

- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java
Added missing include flag and path for modules for linux
> 5998-missing-command-line-arg-for-regripper-on-linux

- KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/AdHocSearchChildFactory.java
Moved position of keyword preview from back of map to front so it will display in proper order for viewing.
> 5638-keyword-preview-is-on-far-right-for-ad-hoc-searches

- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java
Add mpmru parsing, change where artifacts are added in adobemru so it does not get checked every time.
> 5342-Create-artifacts-for-recently-used-Windows-Media-Player-files-from-regripper-output

- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java
- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/RecentDocumentsByLnk.java
normalize path names with unix/linux format instead of windows in Recent Documents by LNK and Recent Doc MRU's
> 6074-Standardize-file-paths-in-recent-documents-to-match-format-that-is-stored-in-autopsy-database

- Running_Linux_OSX.txt
On macOS one has to install the `liberica-jdk8-full` package in order to have OpenJFX.
The `liberica-jdk8` package **does not work correctly with Autopsy.**
> Update installation instructions for macOS

- Core/src/org/sleuthkit/autopsy/core/ServicesMonitor.java
This PR has no behavior changes, just some reorganization and comment updates, excepting:
- Adding an empty string check to an existing null service name check.
- Adding omitted logging of the details argument to setServiceStatus.
> Tidy up the ServiceMonitor class

- Core/src/org/sleuthkit/autopsy/geolocation/MapWaypoint.java
Change colr for TSK_METADATA_EXIF from cyan to Magenta
> 6571-Change-color-in-Geolocation-so-GPS-Route-and-EXIF-Metadata-are-different

- Core/src/org/sleuthkit/autopsy/timeline/actions/SaveSnapshotAsReport.java
When cancel is selected actually cancel and not create report.
> 6653-Timeline-snapshot-report-is-generated-even-if-the-user-hits-cancel

- Core/src/org/sleuthkit/autopsy/modules/pictureanalyzer/impls/HEICProcessor.java
There is a bug when ingesting a data source more than once. For each file, the processor redirects ImageMagick error output to the file's module output directory. Multiple runs result in a FileAlreadyExistsException. Re-running the module should just delete this output file if it exists, since the output file needs to reflect the most recent run.
> Bug fix for HEICProcessor

- thirdparty/rr/plugins/autopsyusb.pl
Comment out lines that issue errors as they are not needed in the file.
> 6924-Error-parsing-output-of-custom-Autopsy-RegRipper-plugins

- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractPrefetch.java
Change Collection type from list to set avoid duplicate timestamps.  Added check to see if artifact already exists before tryng to add it back in, this will help with reruns of RA.
> 7044-duplicate-prefetch-entries

- Experimental/src/org/sleuthkit/autopsy/experimental/configuration/MultiUserTestTool.java
Hello,
after setting up a multi user environment in Linux the test fails and tells me that I have insufficient privileges to create a file.
I tracked the error down when the `MultiUserTestTool` class is creating a temporary file: https://github.com/sleuthkit/autopsy/blob/4c66d9b4e610c3d462dd3a16ba8f4fba36fc4220/Experimental/src/org/sleuthkit/autopsy/experimental/configuration/MultiUserTestTool.java#L156
The problem is that at least in Linux the environment variable `java.io.tmpdir` contains by default the string: `"/tmp"`
That means the concatenation will create a string like that:
`String tempFilePath = "/tmpAutopsyTempFile_<timestamp>.txt"`
So autopsy tries to create a file in the root directory `/`. But the file should be created in the `/tmp` directory.
With my fix there's a …
> [MultiUserTestTool] fix for wrong created temporary file

- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/SearchEngineURLQueryAnalyzer.java
Replace % with %25 in the url before trying to decode it.
> 3997-IllegalArgumentException-in-RecentActivity.SearchEngineURLQueryAnalyzer

- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractZoneIdentifier.java
Catch exception of invalid number and report what file it occured on.  Field is expected to be integer but is not as it appears to have some corruption in it.
> 7177-NumberFormatException-in-RecentActivity

- Running_Linux_OSX.txt
For MacOS in 2021:
brew cask install is no longer valid and has since been replaced with brew install --cask 
check https://brew.sh
> update brew cask install to brew install --cask

- thunderbirdparser/src/org/sleuthkit/autopsy/thunderbirdparser/ThunderbirdMboxFileIngestModule.java
Remove code to not duplicate creating an associated artifact.
> 7310-Duplicate-Associated-Object-artifacts-for-email

- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractPrefetch.java
Sanitize name to avoid having write issues to file system when an ads file is encountered.
> 7523-Escape-prefetch-file-name-when-prefetch-file-is-an-alternate-data-stream

- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ChromeCacheExtractor.java
Check if a zero byte file and do not process it, if it is.
> 7098-BufferUnderflowException-in-Chromium-sub-module-of-Recent-Activity-module

- Core/test/unit/src/org/sleuthkit/autopsy/datasourcesummary/datamodel/DataSourceInfoUtilitiesTest.java
- Core/test/unit/src/org/sleuthkit/autopsy/datasourcesummary/datamodel/UserActivitySummaryTest.java
I also removed the `(long)` cast to remove a warning.
> unit test fixes for changes in blackboard artifact type constructors

- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractRegistry.java
Install date from regripper is UTC time, when it is parsed it does not recognize a timezone so it defaults to current timezone of pc, or that appears to happen.  When  UTC timezone added to parse it stores the epoch time correctly.
> store windows install date as gmt

- Core/src/org/sleuthkit/autopsy/centralrepository/eventlisteners/CaseEventListener.java
Add break statement to only get the first occurence in the CR
> fix-duplicate-interesting-hits-cr-osaccounts

- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractPrefetch.java
Changed dataSource.getName() to dataSource.getId() to avoid any illegal characters when using a local disk as a datasource
> 7824-Illegal-character-reported-in-Recent-Activity

- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/ExtractZoneIdentifier.java
Try catch for IllegalArgument when it is thrown.  log message and continue on processing
> 8008-IllegalArgumentException-in-RA-ExtractZoneIdentifier-module

- InternalPythonModules/android/contact.py
There doesn't appear to be a version of addContact() in CommunicationArtifactsHelper that takes an ingest job ID.
> Remove jobId parameter

- RecentActivity/src/org/sleuthkit/autopsy/recentactivity/Chromium.java
Check if JsonPrimitive before processing.
> 8436-Exception-in-chrome-analyzer

- Core/src/org/sleuthkit/autopsy/casemodule/Bundle.properties
- Core/src/org/sleuthkit/autopsy/casemodule/Bundle.properties-MERGED
- Core/src/org/sleuthkit/autopsy/casemodule/LocalFilesPanel.form
- Core/src/org/sleuthkit/autopsy/casemodule/LocalFilesPanel.java
Add ability to delete a logical filer/directory from DSP panel.  This was requested in https://github.com/sleuthkit/autopsy/issues/7347
> Add ability to delete a logical file/directory from DSP panel
